#!/usr/bin/env python
# coding: utf-8

# # Test Distance Based Localization on real cases


import copy
import json
import time

import numpy as np
import numpy.typing as npt
import polars as pl
import xtgeo
from ert.storage import open_storage
from surfio import IrapHeader, IrapSurface

from iterative_ensemble_smoother.esmda import ESMDA
from iterative_ensemble_smoother.experimental import DistanceESMDA

"""
This script will read info to test distance-based localisation from various sources:
1. Prediction of response parameters are fetched from ERT storage
2. Observations are fetched from both storage and also read from file where also
   (x,y) position of well with production data or (x,y) position of
   4D seismic observation point is saved. The two input csv formatted files
   with production data are generated by running a script in
   RMS workflow where it is possible to get the well positions or average well path
   position (per zone). Well position is taken from RMS well paths while the well
   production observations are currently taken from ERT input observation file for
   SUMMARY data from flow simulator. Seismic observations are read from the FMU
   project where tables of seismic observations with position is available.
   Both observations of production data (corresponding to SUMMARY vectors from
   flow simulator) and seismic observations can be associated with geological
   zones. If not, the observations are assumed to be relevant to update parameters
   for all geological zones.
   NOTE: Need to create observation input files for RFT and PLT and TRACER data.
   All these data types can be associated with a well position (RFT, PLT) or
   a set of well positions (TRACER).
3. Ensemble of realizations of all parameters (both scalar and field parameters)
   is fetched from ERT storage.
4. The definition of ERTBOX for each field parameter should be possible to get
   from storage. This information is currently defined by a hard-coded dict
   in this script.

Use of observations:
1. First a dict with all observations are built based on combining the information about
   observations from both storage and external files read. This must be created such
   that it is easy to identify which observations belongs to which zones.
   Default will be that observations belongs to all zones.
2. Secondly, for all observations that cannot be associated with a single position,
   the position data is marked as None existing, but still they must be used.
3. Check if there are zone dependent observations (not available in all zones)
   and define groups of observations per zone.

Responses and observations:
1. For each zone, calculate Y matrix using responses, observation vector and covariance
   diagonal matrix C_D for observation error. If multiple zone use the same set of
   observations, we can re-use Y, observation vector and C_D instead of
   re-calculating it. Some data structure to handle this should be on the
   implementation plan. This step will be the first step before running update
   calculation of batches of layers of field parameter values from a field
   parameter group. But if re-use of Y, observation vector and C_D is possible
   without reaching memory limit, some time will be saved.

Update steps:
1. Preparation step: Group observations per zone
2. For each geological zone:
    - Get the observation group for the zone.
    - If not yet calculated and available, calculate Y, observation vector, C_D
    - If not yet calculated and available, calculate rho for one layer of the 3D grid.
        The calculation of rho for one layer depends on the observation positions
        and the position of the center point of each grid cell in the
        ERTBOX laterally (i,j).
        It also depends on parameters for localization ellipse
        (the ellipse principal axes corresponds to main range and perpendicular ranges
        and the ellipse is rotated) for each observation. The influence range parameters
        can be individual per observation.

        For irregularly distributed observation points like observations coming from
        production data from wells, the calculation of rho for one grid layer of the
        parameters is done by using numpy mesh in distance calculations.
        For regularly spaced observations (typically seismic observation points), it is
        more efficient to only calculate rho for pairs of field parameter values and
        seismic observation points by calculating ranges of indices in the ertbox grid
        and the seismic grid (if the seismic grid which is usually a 2D grid) is
        aligned with the ERTBOX (same rectangular area as a layer of ERTBOX as seen in
        map view (xy- cross section)).
        The resolution (the spacing) between seismic observation points in local x and y
        direction within the ERTBOX can be different from the ERTBOX.
        Utilize the regular grid structure of seismic data, assuming it is aligned with
        ERTBOX, reduces the need for calculating distance between all pairs of grid cell
        center points of ERTBOX, which is the position of the field parameter values,
        and each individual observation point of the seismic observation.

        Note: For observation with None as position (for instance region observations
        like fluid contacts, production observation for regions or the whole reservoir)
        rho for these type of observation is 1 for all field parameter values in
        a group or even for all parameter groups depending on whether the observation
        is limited to specified zone(s). If the user want to limit the non-local
        observations influence radius around some user specified position, it should
        be possible for the user to specify this, but default should be that region
        related observations are non-local and will have influence on all parameters.
        (Corresponds to infinite localization ranges)
    - Initialize smoother object
    - Calculate all steps that only depends on Y, observations and C_D
      as preparation step.
    - Loop over parameters and for 3D field parameters:
        - Loop over batches of layers of field parameter values from a field parameter
          group.
        - Within the loop, copy rho for one layer into all layers in the batch of
          layers to get the rho for the update.
        - Run assimilate to calculate the update for this batch
        - Repeat for all batches of layers of field parameters

The optimization of the algorithm is here related to:
1. Calculate rho for one layer for a 3D field parameter and copy it into the other
   layers since distance is only calculated laterally (z coordinate is not used),
   but still observations can be limited to update a subset of all geological zones,
   so in that sense it may be depth dependent, but only on a coarse scale
   (zone scale). To take care of this we have the loop over zones.

   The calculation of rho for one layer can be optimized if observations
   (like seismic observation points) and the field parameter is aligned within ERTBOX.
   This means that both field parameter and seismic obs
   are regularly spaced and can be calculated in the same local coordinate system
   defined by ERTBOX.
   A local coordinate system is defined by the ERTBOX. The ERTBOX coordinate system
   is defined by a corner point (lower left) (xorigo, yorigo) in global coordinates
   (e.g. UTM coordinates). A rotation of the ERTBOX define the rotation of the local
   coordinate system relative to the global coordinate system.
   Note that in general ERTBOX coordinate system may vary from field parameter to field
   parameter, but usually the ERTBOX coordinate system is the same for all zones while
   the grid resolution of the ERTBOX grid may vary from zone to zone, in particular
   the number of layers, nz. Some calculations can be saved by knowing if all field
   parameters share the same definition of the ERTBOX coordinate system or not,
   which means that (xorigo, yorigo, rotation) is the same and that the grid resolution
   laterally (xinc, yinc, nx, ny ) is the same.
   A position of a field parameter witin ERTBOX coordinate is
     xpos =  (i+0.5) * xinc
     ypos =  (j+0.5) * yinc
   where local origo is (0,0) and is the same position as the rotation point
   (xorigo, yorigo) for ERTBOX relative to the global coordinate system.

   Observation position is translated and rotated to get the coordinates in ERTBOX
   coordinate system.
     a. Translate observation position to lower left corner point of ERTBOX
        (if ERTBOX is not rotated)
     b. Rotate to the local coordinate axes of the ERTBOX

   After position of observations are transformed into ERTBOX coordinates,
   it is possible to calculate distances between observations and field parameter
   grid cells in ERTBOX. If seismic data is aligned with the ERTBOX and the rows
   and columns of regularly spaced observation points are oriented in same way as
   the cell center points in the ERTBOX grid, it is relatively easy to calculate
   intervals of cell indices in i and j direction for the field parameter
   grid cells within range of a seismic observation. This can speed up the
   calculation a bit instead of having to calculate the distance between each
   individual seismic point and each individual field parameter position.

   Note: There are currently no information telling ERT which zone a field
   parameter belongs to. Field parameters generated by the APS facies method
   follow a naming standard where zone name is part of the field parameter name.
   Example: aps_<zone_name>_<gaussian_field_name> like aps_Valysar_GRF1.
   For field parameters related to petrophysical properties (permeability, porosity)
   which is updated simultaneously with gaussian fields used by the APS facies model to
   create facies, a proposal for a naming convention is to use
   <zone_name>_<facies_name>_<petrophysical_name> for field parameters for petrophysical
   fields related to one particular zone and facies.
   For cases where petrophysical properties is used as (transformed) gaussian fields
   and not dependent on facies, the naming convention could be
   <zone_name>_<petrophysical_name>.
   If we use a naming convention like this, ERT can without any additional information
   identify which 3D field parameters belongs to which geological zone. If no naming
   standard is required it is need for an additional information where zone name is
   specified per FIELD keyword in ERT config file.
   In the current script, which zone a field parameter group belongs to is
   hard-coded in a dict.

   NOTE: In the update algorithm it is required (for efficiency) and for calculation
   of rho that we know which type of parameter a parameter group is.
   This information is also lacking in the storage?
   But maybe it is possible to infer it from the data types used?
   In the current script, the info about which type of parameter each group
   belongs to is hard-coded in a dict. The parameter types are either
   specified by keyword FIELD (3D), SURFACE (2D) or
   GEN_KW (scalar parameters). Depending on the type,
   different calculations of rho and of batching is applied.
   Scalar parameters are not updated by distance-based smoother algorithm,
   but can be updated by Adaptive smoother algorithm.

2. Calculation of Y, C_D and many steps in the distance-based update algorithm
   within DistanceESMDA can be done once for each field parameter group and not
   necessary to re-calculate for each batch of field parameters belonging to the
   same field parameter group. If multiple field parameters are influenced by the
   same set of observations, they can use the same Y, C_D and observation vector
   and thereby save run time.

3. Define batches of field parameters to be update simultaneously.
   Default can be to update all parameters in a parameter group together,
   but if the 3D fields are large, it may be necessary to split the field parameters
   into a set of layers of parameters. The calculation of batch size should then
   not only depend on current max available memory but rounded down to define a batch
   of complete set of layers of parameters and avoid including e.g 10 complete
   layers and a fraction of layer number 11.
   Then choose the batch size to be 10 layers instead.
   It will then be easier to copy rho for one complete layer into the
   10 complete layers of parameters for the batch.

4. Optimalization of multiplication of kalmain gain matrix K with innovation.
   a. Since K with localization will contain a lot of 0 values due to the
      Schur product between rho and K before rho is multiplied,
      time for computation can be saved by avoiding multiplications and additions
      with 0. Particluarly for cases with seismic 4D observations with many
      observations and short localization range around seismic points,
      rho will contain ver large portion of elements with 0 as value.

   b. For all field parameter values (and other parameters) having 0 in
      DeltaM = M - mean(M) due to 0 prior uncertainty it is also not necessary
      to do the calculations. These two potential optimizations should be taken
      care of in implementation since the last two steps in the assimilation
      algorithm take most time due to large matrix multiplication when using seismic
      observations.

   c. The last optimalization potential is for cases where there are large portions
      of inactive field parameters within ERTBOX. Today, we have to calculate an
      update for all field parameters in ERTBOX regardless of whether they are active
      or not since which cells have active field parameter value vary from realization
      to realization in general case.
      If we modify the calculation of DeltaM = M - mean(M) and only use active values
      in mean(M), it will be possible to update the field parameters only for the
      active field parameter values within each realization.
      This will also reduce number of multiplications and additions.
      On the other hand, the filtering operation to select which field parameter
      to update also require some CPU time, so a test for various cases should be done.
      This optimalization is most relevant for geological zones modelled as top or
      base conform where number of active parameters in the geological zone vary
      from realization to realization due to structural model uncertainty.
      For zones with proportional gridding, also the number of active parameters
      may vary due to structural model uncertainty that varies from realization
      to realization, but in this case it is typically along staircase faults
      the number of active parameters may vary from realization to realization.

Drogon case:
1. Assume all observations except RFT and PLT data can update parameters for all zones.
   The lateral influence of an observation will limit how far laterally an observation
   will have effect on field parameters, but vertically the field parameters with
   (x,y) distance within the localization range is updated.
   For zone dependent data like RFT and PLT, they are only included in observation
   vector for the relevant zones. It is possible to experiment with zone dependence
   such that some observations are only able to update field parameters in one zone
   and not all 3 zones.
2. The ERTBOX coordinate system is the same for all zones
   (same lateral definition of ERTBOX). This means that coordinate transformation of
   position of observations is only necessary to be calculated once and
   calculation of rho for one layer can be done once as long as all zones use the
   same observations.
3. The size of the field parameters (nx * ny * nz_zone_dependent) is small enough
   that one usually don't have to split the update of a parameter group into smaller
   batches in this case.
4. The naming convention used by APS allow us to identify the zone name for each
   field parameter group but this is in general not the case and therefore a
   hard-coded dict in this script define the zone per field even though this
   is not necessary when only using field parameters coming from APS where zone name
   is part of the field parameter name in ERT.
5. Number of active parameters vary from realization to realization in Therys,
   but not in the other two zones. There are no large staircase faults that
   creates active/inactive field parameters from realization to realization.

What Drogon case cannot test:
1. A more efficient specification of seismic 4D data defined by a regular 2D grid
   aligned with the ERTBOX.
2. No observation related to regions or the reservoir as a whole.
3. No observation of fluid contacts
  (they are used as parameters with a prior distribution)
4. Drogon size of the field parameters are not very large compared
   with real reservoir cases.
5. Drogon does not limit updates of 2D SURFACE parameters to observations directly
   related to volume, but is updated by using all observations.
6. Cannot test the effect of having active/inactive values varying from realization
   to realization along staircase faults.
"""
TESTS = False
DEBUG_PRINT = True
OUTPUT_PATH = "TMP"
STORAGE_PATH = (
    "/project/fmu/users/olia/drogon_20250623_11-50/"
    "resmod/ff/25.0.0/ert/output/drogon_ahm/storage"
)
EXPERIMENT_NAME = "ensemble_experiment"
ENSEMBLE_NAME = "ensemble"
SEED = 42
ALPHA = 1
TRUNCATION = 0.99
NLAYER_PER_BATCH = (
    66  # 66 layers in ERTBOX for Drogon which is split into 2 batches here
)
# Turn on/off calculation of rho based on localization or only use rho = 1
USE_LOCALIZATION = True

# Turn on/off export of field parameters into 3D parameter
# files in ROFF format to be read by RMS.
WRITE_STATS_PARAMS = True


# Common definition of ERTBOX for all zones in Drogon
XORIGO = 461505
YORIGO = 5926523
XINC = 75.0
YINC = 74.71
ROTATION = 29.88159640627248
NX = 92
NY = 146
NZ = 66
HANDEDNESS = (
    "right"  # Alternatives: "right" or "left" Drogon uses right handed for ERTBOX
)
ERTBOX_GRID_FILE_NAME = "ertbox.roff"
# Need to distinguish between observation groups.
# NOTE: This should be available from ERT, but is not yet?
# WellObs - Observations from wells with position (prod data etc)"
# GenObs  - Any observation having a location like seismic obs points,
#           gravimetry obs points
# RegionObs - Any observation without any specific coordinate for
#             its location (e.g. region or field prod data,
#             data for average over regions, FWL, GOC which are
#             defined per region)
# TODO: In this version of the test script all observations are assumed to have position
# OBS_TYPES_WITH_LOCATION = ["WellObs", "GenObs"]
# OBS_TYPES_WITHOUT_LOCATION = ["RegionObs"]

# Get observations with position and localization ranges from external files
# created by running a script in RMS
# OBS_FILE_PATH = (
#    "/project/fmu/users/olia/drogon_20250623_11-50/resmod/ff/25.0.0/rms/model/"
# )
OBS_FILE_PATH = "./"
# OBS_FILE = "test_obs1.csv"
OBS_FILE = "summary_obs_with_localization_attributes.csv"
OBS_SUMMARY_WITH_LOCAL_ATTRIBUTES_FILE = OBS_FILE_PATH + OBS_FILE


# If we could have naming convention we could get zone name from parameter name.
# We have that for APS parameters:  aps_<zone_name>_<grf_name>),
# In general we don't. A proposal for naming convention for petrophysical
# field parameters (e.g for permeability or porosity) could be
# <zone_name>_<facies>_<petro_name> for petrophysical fields to be updated
# simultaneously with facies update from APS.
# For reservoir zones without facies modelling, the convention could
# be  <zone_name>_<petro_name>
# NOTE: An additional parameter in FIELD keyword with zone name can solve the problem
# if naming convention of 3D field parameters is not required.
# Storage should have zone name as an attribute to each field parameter.
# ZONES = ["Valysar"]
ZONES = ["Valysar", "Therys", "Volon"]
# Is used to assosiate fields with zones for cases where we need to distinguish
# between zones (due to different obs per zone). The first version of this script
# should use obs data frames that are equal for all zones.
ZONE_PER_3D_FIELD_PARAM_GROUP = {
    "aps_Valysar_GRF1": "Valysar",
    "aps_Valysar_GRF2": "Valysar",
    "aps_Valysar_GRF3": "Valysar",
    "aps_Therys_GRF1": "Therys",
    "aps_Therys_GRF2": "Therys",
    "aps_Therys_GRF3": "Therys",
    "aps_Volon_GRF1": "Volon",
    "aps_Volon_GRF2": "Volon",
    "aps_Volon_GRF3": "Volon",
}
# NOTE: ERTBOX should be fetched from the storage, but currently I have specified
# this explicitly here.
#
# Usually ERTBOX definition is the same for all zones (even for NZ), but with the new
# possibility to have individual ERTBOX per geological zone, NZ will usually vary from
# 3D field parameter to 3D field parameter. In more rare cases also
# other ERTBOX definition parameters may vary.
#
# The 3D field parameters belonging to the same zone will also belong to same ERTBOX.
# Depending on observation and their dependency on geological zones, we can simplify
# the calculation of rho:
# 1. If no observations (from well production or seismic) depends on zone,
#    a common version of Y matrix can be used for all zones.
#    It means that localization which only here care about lateral distance (x,y)
#    but not depth will need a calculation of rho for only one grid layer of ERTBOX
#    and this can then be copied to all other layers for the rho for the
#    3D field parameters for the zone.
# 2. If some observations are not defined for all zones, it can be both for
#    seismic 4D and well production observation, then a new version of Y
#    is necessary for each zone.

# For some of the field parameters, the ERTBOX will be the same
# for all ERTBOX parameters. This is the case for field parameters
# coming from the same zone. By identifying which parameters belongs to the same zone
# we can avoid having to recalculate rho matrix for each of these 3D parameters.
# If we have to use batches of layers per field parameter, all the batches for all
# field parameters coming from the same zone can fill rho matrix from the same rho
# calculated for one layer of field parameter values.
# If all observations can update all zones, this can be done even more efficient
# since all 3D field parameters can use the same calculated rho for one single layer.
#
# When ERTBOX is different from field
# parameter to field parameter it is usually because NZ vary
# since the ERTBOX grids for the various zones represents approximately
# the lateral position of a geological grid zone and usually the different
# zones in the geological grid are represented by a multizone grid
# and multi-zone grids usually have the same lateral number of grid cells (NX, NY)
# in each zone. In the most general case, each geological zone has its own geogrid
# with its own orientation, position and resolution and this is possible to represent
# with individual specification of all the ERTBOX parameters per 3D field parameter.
# In Drogon case
# (running a version before 3D field parameters can have individual ERTBOX)
# all ERTBOX parameters are equal as in the case below.
# In the new extended implementation with individual ERTBOX per 3D field parameter,
# I assume each zone of Drogon will have its own value of NZ but the rest is the same.
ERTBOX_PER_3D_FIELD_PARAM_GROUP = {
    "aps_Valysar_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Valysar_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Valysar_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Therys_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Therys_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Therys_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Volon_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Volon_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
    "aps_Volon_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    },
}

SCALING_FUNCTION_NAME = "gaussian"


def monitor_performance(func):
    """Decorator to monitor time only"""

    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()

        result = func(*args, **kwargs)

        end_time = time.perf_counter()

        print(f"Function {func.__name__}:")
        print(f"  Total time: {end_time - start_time:.2f}s")

        return result

    return wrapper


def read_observations_with_localization_attributes(
    filename: str,
) -> pl.DataFrame:
    """
    Read a csv file with space as separator and generated by RMS containing all
    observations of type SUMMARY with (x,y) position in global (UTM) coordinates
    and localization ranges.
    Return a dataframe.
    """
    df_obs_local_attributes = pl.read_csv(filename, separator=" ")
    return df_obs_local_attributes


def transform_to_local_coordinates_3D(
    ertbox_dict: dict,
    xpos: npt.NDArray[np.double],
    ypos: npt.NDArray[np.double],
    ellipse_anisotropy_angle: npt.NDArray[np.double],
) -> tuple[npt.NDArray[np.double], npt.NDArray[np.double], npt.NDArray[np.double]]:
    # Translate
    x1 = xpos - ertbox_dict["xorigo"]
    y1 = ypos - ertbox_dict["yorigo"]
    rotation_of_ertbox = ertbox_dict["rotation"]
    rotation_angle = rotation_of_ertbox * np.pi / 180.0
    cos_theta = np.cos(rotation_angle)
    sin_theta = np.sin(rotation_angle)
    x2 = x1 * cos_theta + y1 * sin_theta
    y2 = -x1 * sin_theta + y1 * cos_theta
    # Both angles measured anti-clock from global coordinate systems x-axis in degrees
    ellipse_anisotropy_transformed = ellipse_anisotropy_angle - rotation_of_ertbox
    return x2, y2, ellipse_anisotropy_transformed


def transform_to_local_coordinates_2D(
    surface_coord_dict: dict,
    xpos: npt.NDArray[np.double],
    ypos: npt.NDArray[np.double],
    ellipse_anisotropy_angle: npt.NDArray[np.double],
) -> tuple[npt.NDArray[np.double], npt.NDArray[np.double], npt.NDArray[np.double]]:
    # Translate
    x1 = xpos - surface_coord_dict["xorigo"]
    y1 = ypos - surface_coord_dict["yorigo"]
    rotation_of_ertbox = surface_coord_dict["rotation"]
    rotation_angle = rotation_of_ertbox * np.pi / 180.0
    cos_theta = np.cos(rotation_angle)
    sin_theta = np.sin(rotation_angle)
    x2 = x1 * cos_theta + y1 * sin_theta
    y2 = -x1 * sin_theta + y1 * cos_theta
    # Both angles measured anti-clock from global coordinate systems x-axis in degrees
    ellipse_anisotropy_transformed = ellipse_anisotropy_angle - rotation_of_ertbox
    return x2, y2, ellipse_anisotropy_transformed


def update_with_esmda(
    storage,
    storage_path: str,
    experiment_name: str,
    ensemble_name: str,
    observations: npt.NDArray[np.double],
    C_D: npt.NDArray[np.double],
    Y: npt.NDArray[np.double],
    n_param_per_group: npt.NDArray[np.int32],
    groups_with_3d_fields: list[str],
    groups_with_2d_fields: list[str],
    groups_with_scalars: list[str],
    seed: int = 42,
    alpha: int = 1,
    write_stats_params: bool = True,
) -> list[
    dict[str, npt.NDArray[np.double]],
    dict[str, npt.NDArray[np.double]],
    str,
    int,
    int,
    int,
]:
    # Workaround to ensure ESMDA don't fail when repeating call on assimilate
    alpha_workaround = np.zeros((1000), dtype=np.float64)
    alpha_workaround[:] = 1.0

    print("Loop over all parameter groups and update with ESMDA")
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    X_prior_dict = {}
    X_posterior_dict = {}
    print(f"{n_param_per_group=}")
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
    ensemble = experiment.get_ensemble_by_name(ensemble_name)
    param_config_all = experiment.parameter_configuration
    groups = list(param_config_all.keys())

    realizations = ensemble.get_realization_list_with_responses()
    for group_number, group_name in enumerate(groups):
        if group_name not in groups_updatable:
            print(f" Skip group {group_name} which cannot be updated")
            continue

        print(
            f"Process parameter group: {group_name} with "
            f"{n_param_per_group[group_number]} parameters"
        )
        if group_name in groups_with_3d_fields:
            print(f" Parameter group {group_name} is a 3D field")
            param_type = "3D"

            nx = param_config_all[group_name].nx
            ny = param_config_all[group_name].ny
            nz = param_config_all[group_name].nz
        elif group_name in groups_with_2d_fields:
            print(f" Parameter group {group_name} is a 2D field")
            param_type = "2D"
            nx, ny, nz = 0, 0, 0
            nx = param_config_all[group_name].ncol
            ny = param_config_all[group_name].nrow
            nz = 1
        elif group_name in groups_with_scalars:
            param_type = "Scalar"
            nx, ny, nz = 0, 0, 0
        else:
            print(f" Warning: {group_name} is of unknown type. Will not be updated.")
            continue

        X_group = ensemble.load_parameters_numpy(group_name, realizations)
        print(f"X_group.shape = {X_group.shape}")
        print(f"Y.shape = {Y.shape}")
        assert Y.shape[1] == X_group.shape[1]

        print(" Assimilate")
        smoother_ESMDA = ESMDA(
            covariance=C_D, observations=observations, alpha=alpha_workaround, seed=seed
        )
        X_post_group = smoother_ESMDA.assimilate(X=X_group, Y=Y)
        X_posterior_dict[group_name] = X_post_group
        X_prior_dict[group_name] = X_group

        print(
            f"Complete ESMDA for parameter group {group_name} with "
            f"{n_param_per_group[group_number]} parameters"
        )
        print("")

        if write_stats_params and param_type == "3D":
            # Optionally, calculate mean stdev and write to file
            mean_prior_param = np.mean(X_group, axis=1)
            stdev_prior_param = np.std(X_group, axis=1)
            mean_post_param = np.mean(X_post_group, axis=1)
            stdev_post_param = np.std(X_post_group, axis=1)
            param_dict = {}
            key = "global_mean_prior_" + group_name
            param_dict[key] = mean_prior_param

            key = "global_std_prior_" + group_name
            param_dict[key] = stdev_prior_param

            key = "global_mean_post_" + group_name
            param_dict[key] = mean_post_param

            key = "global_std_post_" + group_name
            param_dict[key] = stdev_post_param

            write_3D_field_param_to_file(param_dict, nx, ny, nz)
            print("")
    return [X_prior_dict, X_posterior_dict, param_type, nx, ny, nz]


def define_response_and_observations(
    ensemble,
    observations_and_responses: pl.DataFrame,
) -> tuple[
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
    npt.NDArray[np.double],
]:
    """
    Calculate Y matrix, C_D matrix and return numpy vectors with:
    - observations
    - xpos for obs in global coordinates (UTM)
    - ypos for obs in global coordinates (UTM)
    - main_range   influence range (first half-axis in influence ellipse
    - perp_range   influence range (second half-axis in influence ellipse
    - anisotropy_angle  rotation of first half-axis of influence ellipse
      relative to global coordinate system
    """
    response_cols = [str(i) for i in range(0, ensemble.ensemble_size)]

    # Here responses with 0 std is not included?
    df_filtered = observations_and_responses.filter(
        pl.concat_list([pl.col(col) for col in response_cols])
        .list.eval(pl.element().std())
        .list.first()
        > 0
    )

    df_removed = observations_and_responses.filter(
        pl.concat_list([pl.col(col) for col in response_cols])
        .list.eval(pl.element().std())
        .list.first()
        <= 0
    )
    if DEBUG_PRINT:
        print(" Observations removed due to 0 standard deviation of responses:")
        columns_to_print = ["observation_key", "response_key"]
        print(df_removed.select(columns_to_print))

    # Select only realizations of responses

    Y = df_filtered.select(response_cols).to_numpy()

    observations = df_filtered["observations"].to_numpy()
    std = df_filtered["std"].to_numpy()
    C_D = std**2

    xpos = df_filtered["xpos"].to_numpy()
    ypos = df_filtered["ypos"].to_numpy()
    main_ranges = df_filtered["main_range"].to_numpy()
    perp_ranges = df_filtered["perp_range"].to_numpy()
    anisotropy_angle = df_filtered["anisotropy_angle"].to_numpy()

    return Y, observations, C_D, xpos, ypos, main_ranges, perp_ranges, anisotropy_angle


def write_3D_field_param_to_file(
    param_dict: dict[str, npt.NDArray[np.double]],
    nx: int,
    ny: int,
    nz: int,
    output_path: str = "TMP",
) -> None:
    """
    Write 3D parameter to ROFF format file to be readable by RMS
    """
    for param_name, values in param_dict.items():
        xtgeo_param = xtgeo.GridProperty(
            ncol=nx,
            nrow=ny,
            nlay=nz,
            name=param_name,
            values=values,
        )
        file_name = output_path + "/" + param_name + ".roff"
        print(f"  Write file: {file_name}")
        xtgeo_param.to_file(file_name, fformat="roff")


def write_2D_field_param_to_file(
    filename: str,
    surface_coord_dict: dict,
    values: npt.NDArray[np.double],
):
    print(f"  Write file: {filename}")
    surf = IrapSurface(
        header=IrapHeader(
            ncol=surface_coord_dict["nx"],
            nrow=surface_coord_dict["ny"],
            xori=surface_coord_dict["xorigo"],
            yori=surface_coord_dict["yorigo"],
            xinc=surface_coord_dict["xinc"],
            yinc=surface_coord_dict["yinc"],
            rot=surface_coord_dict["rotation"],
            xrot=surface_coord_dict["xrotationpoint"],
            yrot=surface_coord_dict["yrotationpoint"],
        ),
        values=values,
    )
    surf.to_ascii_file(filename)


def scaling_function(
    distances: npt.NDArray[np.double], name: str = "gaussian"
) -> npt.NDArray[np.double]:
    if name.lower() == "gaussian":
        scaling_factor = np.exp(-3.0 * distances**2)
    elif name.lower() == "exponential":
        scaling_factor = np.exp(-3.0 * distances)
    return scaling_factor


def calculate_rho_for_summary_obs_for_one_layer_of_3D_field_old(
    ertbox_dict: dict,
    obs_xpos: npt.NDArray[np.double],
    obs_ypos: npt.NDArray[np.double],
    obs_main_range: npt.NDArray[np.double],
    obs_perp_range: npt.NDArray[np.double],
    obs_anisotropy_angle: npt.NDArray[np.double],
    scaling_function_name: str = "gaussian",
) -> npt.NDArray[np.double]:
    """
    Input:
    Specification of ERTBOX for the field
    (xorigo, yorigo,rotation,xinc,yinc,nx,ny,nz)
    Position (obs_xpos, obs_ypos), localization ranges
    (obs_main_range, obs_perp_range, obs_anisotropy_angle)
    for well observations only.
    The input position must be transformed into the local coordinate system
    defined by the ERTBOX, and the influence range and anisotropy_angle
    must also be relative to the local coordinate system defined by the ERTBOX.
    The position: xpos[n], ypos[n],
    localization ellipse defined by: main_range[n],perp_range[n], anisotropy_angle[n])
    refers to observation[n]
    Output: rho for one layer with nx * ny field parameter values for all observations
    having position.
    RHO[[n,m] =
    taperingfunc(distance((xpos_obs[n],ypos_obs[n]),(xpos_field[i,j,k],ypos_field[i,j,k]))
    where m = i + j* nx + k * nx * ny
    Note that:
    distance(   (xpos_obs[n],ypos_obs[n]), (xpos_field[i,j,k1], ypos_field[i,j,k1]) ) =
    distance(   (xpos_obs[n],ypos_obs[n]), (xpos_field[i,j,k2], ypos_field[i,j,k2]) )
    for all k1, k2 in [0,nz-1]  since distance calculation is only lateral.
    """
    # Center points of each grid cell in field parameter grid
    # in local coordinate system (ertbox grid)
    nx = ertbox_dict["nx"]
    ny = ertbox_dict["ny"]
    handedness = ertbox_dict["handedness"]
    x_local = np.arange(nx)
    x_local = (x_local + 0.5) * ertbox_dict["xinc"]
    if handedness == "right":
        # Order y from max to min y
        y_local = np.arange(ny - 1, -1, -1, dtype=np.float64)
    else:
        # Order y from min to max y
        y_local = np.arange(ny, dtype=np.float64)

    y_local = (y_local + 0.5) * ertbox_dict["yinc"]
    mesh_x_coord, mesh_y_coord = np.meshgrid(x_local, y_local, indexing="ij")
    # mesh_y_coord, mesh_x_coord = np.meshgrid(y_local, x_local, indexing="ij")
    nobs = len(obs_xpos)
    assert nobs == len(obs_ypos)
    assert nobs == len(obs_anisotropy_angle)
    assert nobs == len(obs_main_range)
    assert nobs == len(obs_perp_range)
    nparam_per_layer = nx * ny
    rho_one_layer = np.ones((nparam_per_layer, nobs), dtype=np.float64)
    for obs_number in range(len(obs_xpos)):
        xpos = obs_xpos[obs_number]
        ypos = obs_ypos[obs_number]
        anisotropy_angle = obs_anisotropy_angle[obs_number]
        main_range = obs_main_range[obs_number]
        perp_range = obs_perp_range[obs_number]
        dX = mesh_x_coord - xpos
        dY = mesh_y_coord - ypos
        rotation = anisotropy_angle * np.pi / 180.0
        cosangle = np.cos(rotation)
        sinangle = np.sin(rotation)
        dX_ellipse = (dX * cosangle + dY * sinangle) / main_range
        dY_ellipse = (-dX * sinangle + dY * cosangle) / perp_range
        distances_2d = np.sqrt(dX_ellipse * dX_ellipse + dY_ellipse * dY_ellipse)
        distances = distances_2d.flatten()
        rho_one_layer[:, obs_number] = scaling_function(
            distances, name=scaling_function_name
        )
    return rho_one_layer


def calculate_rho_for_summary_obs_for_one_layer_of_3D_field(
    ertbox_dict: dict,
    obs_xpos: npt.NDArray[np.double],
    obs_ypos: npt.NDArray[np.double],
    obs_main_range: npt.NDArray[np.double],
    obs_perp_range: npt.NDArray[np.double],
    obs_anisotropy_angle: npt.NDArray[np.double],
    scaling_function_name: str = "gaussian",
) -> npt.NDArray[np.double]:
    # TODO: Check index order maybe it should be C order here instead
    """
    Input:
    Specification of ERTBOX for the field
    (xorigo, yorigo,rotation,xinc,yinc,nx,ny,nz)
    Position (obs_xpos, obs_ypos), localization ranges
    (obs_main_range, obs_perp_range, obs_anisotropy_angle)
    for well observations only.
    The input position must be transformed into the local coordinate system
    defined by the ERTBOX, and the influence range and anisotropy_angle must
    also be relative to the local coordinate system defined by the ERTBOX.
    The position: xpos[n], ypos[n] and
    localization ellipse defined by obs_main_range[n],obs_perp_range[n],
    obs_anisotropy_angle[n]) refers to observation[n]
    Output: rho for one layer with nx * ny field parameter values for
    all observations having position.
    RHO[[n,m] =
    taperingfunc(distance((xpos_obs[n],ypos_obs[n]),(xpos_field[i,j,k],ypos_field[i,j,k]))
    where m = i + j* nx + k * nx * ny for left-handed grid index origo and
    m = i + (ny - j - 1) * nx + k * nx * ny for right-handed grid index origo
    Note that:
    distance(   (xpos_obs[n],ypos_obs[n]), (xpos_field[i,j,k1], ypos_field[i,j,k1]) ) =
    distance(   (xpos_obs[n],ypos_obs[n]), (xpos_field[i,j,k2], ypos_field[i,j,k2]) )
    for all k1, k2 in [0,nz-1]  since distance calculation is only lateral.

    """
    # Center points of each grid cell in field parameter grid
    nx = ertbox_dict["nx"]
    ny = ertbox_dict["ny"]
    handedness = ertbox_dict["handedness"]
    x_local = (np.arange(nx, dtype=np.float64) + 0.5) * ertbox_dict["xinc"]
    if handedness == "right":
        # y coordinate descreases from max to min
        y_local = (np.arange(ny - 1, -1, -1, dtype=np.float64) + 0.5) * ertbox_dict[
            "yinc"
        ]
    else:
        # y coordinate increases from min to max
        y_local = (np.arange(ny, dtype=np.float64) + 0.5) * ertbox_dict["yinc"]
    mesh_x_coord, mesh_y_coord = np.meshgrid(x_local, y_local, indexing="ij")
    # mesh_y_coord, mesh_x_coord = np.meshgrid(y_local, x_local, indexing="ij")
    print(f"{mesh_x_coord.shape=}")
    print(f"{mesh_y_coord.shape=}")
    # Number of observations
    nobs = len(obs_xpos)
    assert nobs == len(obs_ypos)
    assert nobs == len(obs_anisotropy_angle)
    assert nobs == len(obs_main_range)
    assert nobs == len(obs_perp_range)

    # Prepare rho array
    nparam_per_layer = nx * ny
    rho_one_layer = np.ones((nparam_per_layer, nobs), dtype=np.float64)

    # Expand grid coordinates to match observations
    mesh_x_coord_flat = mesh_x_coord.flatten()[:, np.newaxis]  # (nx * ny, 1)
    mesh_y_coord_flat = mesh_y_coord.flatten()[:, np.newaxis]  # (nx * ny, 1)

    # Observation coordinates and parameters
    obs_xpos = obs_xpos[np.newaxis, :]  # (1, nobs)
    obs_ypos = obs_ypos[np.newaxis, :]  # (1, nobs)
    obs_main_range = obs_main_range[np.newaxis, :]  # (1, nobs)
    obs_perp_range = obs_perp_range[np.newaxis, :]  # (1, nobs)
    obs_anisotropy_angle = obs_anisotropy_angle[np.newaxis, :]  # (1, nobs)

    # Compute displacement between grid points and observations
    dX = mesh_x_coord_flat - obs_xpos  # (nx * ny, nobs)
    dY = mesh_y_coord_flat - obs_ypos  # (nx * ny, nobs)

    # Compute rotation parameters
    rotation = obs_anisotropy_angle * np.pi / 180.0  # (1, nobs)
    cos_angle = np.cos(rotation)  # (1, nobs)
    sin_angle = np.sin(rotation)  # (1, nobs)

    # Rotate and scale displacements to local coordinate system defined
    # by the two half axes of the influence ellipse. First coordinate (local x) is in
    # direction defined by anisotropy angle and local y is perpendicular to that.
    # Scale the distance by the ranges to get a normalized distance
    # (with value 1 at the edge of the ellipse)
    dX_ellipse = (dX * cos_angle + dY * sin_angle) / obs_main_range  # (nx * ny, nobs)
    dY_ellipse = (-dX * sin_angle + dY * cos_angle) / obs_perp_range  # (nx * ny, nobs)

    # Compute distances in the elliptical coordinate system
    distances = np.sqrt(dX_ellipse**2 + dY_ellipse**2)  # (nx * ny, nobs)

    # Apply the scaling function
    rho_one_layer = scaling_function(
        distances, name=scaling_function_name
    )  # (nx * ny, nobs)

    if DEBUG_PRINT:
        print(f"  {rho_one_layer.shape=}")
    return rho_one_layer


def calculate_rho_for_summary_obs_for_2D_field(
    surface_coord_dict: dict,
    obs_xpos: npt.NDArray[np.double],
    obs_ypos: npt.NDArray[np.double],
    obs_main_range: npt.NDArray[np.double],
    obs_perp_range: npt.NDArray[np.double],
    obs_anisotropy_angle: npt.NDArray[np.double],
    scaling_function_name: str = "gaussian",
) -> npt.NDArray[np.double]:
    """
    Calculates rho for all 2D field parameters in a SURFACE parameter.
    Assumption 1: The surface defines a local coordinate defined by
    the surface_dict containing (xorigo, yorigo, xinc, yinc, rotation, nx, ny)
    for the surface.
    Assumption 2: The localization ranges and orientation of the ellipse for
    influence is the same for 2D surface parameters as for  3D field parameters.
    Assumption 3: Input position of well observations is already transformed into
    the local coordinate system defined by the surface.

    Input: Definition of local surface coordinates, position and localization ranges
    for observations for well observations only.
    The input position must be transformed into the local coordinate system
    defined by the local surface coordinates ,and the influence range and
    obs_anisotropy_angle must also be relative to the local coordinate system
    defined by the surface.
    The position: xpos[n], ypos[n] and
    localization ellipse defined by main_range[n],perp_range[n], anisotropy_angle[n])
    refers to observation[n]
    Output: rho for surface parameter with nx * ny field parameter values for all
    observations having position.
    RHO[[n,m] =
    taperingfunc(distance((xpos_obs[n],ypos_obs[n]), (xpos_field[i,j], ypos_field[i,j]))
    where m = i + j* nx
    """
    # Center points of each grid cell in field parameter grid
    nx = surface_coord_dict["nx"]
    ny = surface_coord_dict["ny"]
    x_local = (np.arange(nx) + 0.5) * surface_coord_dict["xinc"]
    y_local = (np.arange(ny) + 0.5) * surface_coord_dict["yinc"]
    mesh_y_coord, mesh_x_coord = np.meshgrid(y_local, x_local, indexing="ij")

    # Number of observations
    nobs = len(obs_xpos)
    assert nobs == len(obs_ypos)
    assert nobs == len(obs_anisotropy_angle)
    assert nobs == len(obs_main_range)
    assert nobs == len(obs_perp_range)

    # Prepare rho array
    nparam_per_layer = nx * ny
    rho_one_layer = np.ones((nparam_per_layer, nobs), dtype=np.float64)

    # Expand grid coordinates to match observations
    mesh_x_coord_flat = mesh_x_coord.flatten()[:, np.newaxis]  # (nx * ny, 1)
    mesh_y_coord_flat = mesh_y_coord.flatten()[:, np.newaxis]  # (nx * ny, 1)

    # Observation coordinates and parameters
    obs_xpos = obs_xpos[np.newaxis, :]  # (1, nobs)
    obs_ypos = obs_ypos[np.newaxis, :]  # (1, nobs)
    obs_main_range = obs_main_range[np.newaxis, :]  # (1, nobs)
    obs_perp_range = obs_perp_range[np.newaxis, :]  # (1, nobs)
    obs_anisotropy_angle = obs_anisotropy_angle[np.newaxis, :]  # (1, nobs)

    # Compute displacement between grid points and observations
    dX = mesh_x_coord_flat - obs_xpos  # (nx * ny, nobs)
    dY = mesh_y_coord_flat - obs_ypos  # (nx * ny, nobs)

    # Compute rotation parameters
    rotation = obs_anisotropy_angle * np.pi / 180.0  # (1, nobs)
    cos_angle = np.cos(rotation)  # (1, nobs)
    sin_angle = np.sin(rotation)  # (1, nobs)

    # Rotate and scale displacements to anisotropic coordinate system
    dX_ellipse = (dX * cos_angle + dY * sin_angle) / obs_main_range  # (nx * ny, nobs)
    dY_ellipse = (-dX * sin_angle + dY * cos_angle) / obs_perp_range  # (nx * ny, nobs)

    # Compute distances in the elliptical coordinate system
    distances = np.sqrt(dX_ellipse**2 + dY_ellipse**2)  # (nx * ny, nobs)

    # Apply the scaling function
    rho_one_layer = scaling_function(
        distances, name=scaling_function_name
    )  # (nx * ny, nobs)
    return rho_one_layer


def get_3D_field_parameter_names_per_zone(
    groups, param_config_all, zone_per_field_param_group: dict
) -> dict[str, list[str]]:
    """
    Scan through all parameter groups. Get the groups of type 3D field parameters.
    Store the field parameter names per zone in a dict. All field parameter belonging
    to the same zone has the same ERTBOX grid and can use the same local coordinate
    system.
    Output: dict with zone as key and value is a list of field parameter names.
    """
    # Define a list of field parameters per zone.
    field_param_3d_list_per_zone_dict = {}
    for group_name in groups:
        if param_config_all[group_name].type == "field":
            zone_name = zone_per_field_param_group[group_name]
            if zone_name in field_param_3d_list_per_zone_dict:
                field_param_3d_list_per_zone_dict[zone_name].append(group_name)
            else:
                field_param_3d_list_per_zone_dict[zone_name] = [group_name]
    return field_param_3d_list_per_zone_dict


def get_2D_field_parameter_names(groups, param_config_all) -> list[str]:
    """
    Get a list of all 2D field parameters (from keyword SURFACE in ERT config file)
    """
    param_names = []
    for group_name in groups:
        if param_config_all[group_name].type == "surface":
            param_names.append(group_name)
    return param_names


# def update_3d_param_with_distance_esmda_old(
#     distance_based_esmda_smoother,
#     field_param_name: str,
#     ensemble,
#     realizations,
#     Y: np.ndarray,
#     obs_xpos: np.ndarray,
#     obs_ypos: np.ndarray,
#     obs_main_ranges: np.ndarray,
#     obs_perp_ranges: np.ndarray,
#     obs_ellipse_rotation: np.ndarray,
#     rho_one_layer: np.ndarray,
#     nlayer_per_batch: int,
#     nx: int,
#     ny: int,
#     nz: int,
# ):
#     """
#     Update 3D field parameter with distance-based ESMDA
#     """
#     nobs = len(obs_xpos)
#     assert nobs == len(obs_ypos)
#     assert nobs == len(obs_main_ranges)
#     assert nobs == len(obs_perp_ranges)
#     assert nobs == len(obs_ellipse_rotation)
#     assert nobs == Y.shape[0]

#     nparam_per_layer = nx * ny

#     print(f" Field name: {field_param_name}")

#     X_group = ensemble.load_parameters_numpy(field_param_name, realizations)
#     nparam, nreal = X_group.shape
#     X_post_group = np.zeros((nparam, nreal), dtype=np.float32)
#     nbatch = int(nz / nlayer_per_batch)
#     nlayer_last_batch = nz - nbatch * nlayer_per_batch
#     for batch_number in range(nbatch):
#         print(f" Batch number: {batch_number}")
#         start_layer_number = batch_number * nlayer_per_batch
#         end_layer_number = start_layer_number + nlayer_per_batch
#         start = start_layer_number * nparam_per_layer
#         end = end_layer_number * nparam_per_layer
#         X_batch = X_group[start:end, :]

#         print(f" Define rho for 3D field {field_param_name}")
#         nparam_in_batch = nparam_per_layer * nlayer_per_batch
#         rho_batch = np.ones(shape=(nparam_in_batch, nobs), dtype=np.float32)
#         # Copy rho calculated from one layer of 3D parameter into all layers for
#         # current batch of layers
#         for layer in range(nlayer_per_batch):
#             from_param = layer * nparam_per_layer
#             to_param = from_param + nparam_per_layer
#             rho_batch[from_param:to_param, :] = rho_one_layer[:]

#         print(f" rho.shape:  {rho_batch.shape}")
#         assert Y.shape[1] == X_batch.shape[1]

#         print(f" Assimilate batch number {batch_number}")
#         X_post_batch = distance_based_esmda_smoother.assimilate_batch(
#             X_batch=X_batch, Y=Y, rho_batch=rho_batch
#         )
#         X_post_group[start:end, :] = X_post_batch[:]

#     if nlayer_last_batch > 0:
#         batch_number = nbatch
#         start_layer_number = batch_number * nlayer_per_batch
#         end_layer_number = start_layer_number + nlayer_last_batch
#         start = start_layer_number * nparam_per_layer
#         end = end_layer_number * nparam_per_layer
#         X_batch = X_group[start:end, :]

#         print(f" Define rho for 3D field {field_param_name}")
#         nparam_in_batch = nparam_per_layer * nlayer_last_batch
#         rho_batch = np.ones(shape=(nparam_in_batch, nobs), dtype=np.float32)
#         # Copy rho calculated from one layer of 3D parameter into all layers for
#         # current batch of layers
#         for layer in range(nlayer_per_batch):
#             from_param = layer * nparam_per_layer
#             to_param = from_param + nparam_per_layer
#             rho_batch[from_param:to_param, :] = rho_one_layer[:]
#         print(f" Define rho for 3D field {field_param_name}")
#         print(f" rho.shape:  {rho_batch.shape}")
#         assert Y.shape[1] == X_batch.shape[1]

#         print(f" Assimilate batch number {batch_number}")
#         X_post_batch = distance_based_esmda_smoother.assimilate_batch(
#             X_batch=X_batch, Y=Y, rho_batch=rho_batch
#         )
#         X_post_group[start:end, :] = X_post_batch[:]

#     return X_post_group


def update_3D_field_with_distance_esmda(
    distance_based_esmda_smoother,
    field_param_name: str,
    ensemble,
    realizations,
    Y: npt.NDArray[np.double],
    rho_one_layer: npt.NDArray[np.double],
    nlayer_per_batch: int,
    nx: int,
    ny: int,
    nz: int,
) -> list[npt.NDArray[np.double], npt.NDArray[np.double]]:
    """
    Calculate posterior update with distance-based ESMDA for one 3D parameter
    The RHO for one layer of the 3D field parameter is input.
    This is copied to all other layers of RHO in each batch of grid parameter
    layers since only lateral distance is used when calculating distances.
    Result is prior and posterior parameter matrices of field parameters for one field.
    """
    nparam = nx * ny * nz
    nparam_per_layer = nx * ny
    nobs = Y.shape[0]

    print(f"   Calculate update for {field_param_name} with {nparam} parameters")
    X_group = ensemble.load_parameters_numpy(field_param_name, realizations)
    assert nparam == X_group.shape[0]
    nreal = X_group.shape[1]
    X_post_group = np.zeros((nparam, nreal), dtype=np.float64)
    nbatch = int(nz / nlayer_per_batch)
    nlayer_last_batch = nz - nbatch * nlayer_per_batch
    for batch_number in range(nbatch):
        print(f"     Batch number: {batch_number}")
        start_layer_number = batch_number * nlayer_per_batch
        end_layer_number = start_layer_number + nlayer_per_batch
        start = start_layer_number * nparam_per_layer
        end = end_layer_number * nparam_per_layer
        X_batch = X_group[start:end, :]

        print(f"     Define rho for 3D field {field_param_name}")
        nparam_in_batch = nparam_per_layer * nlayer_per_batch
        rho_batch = np.ones(shape=(nparam_in_batch, nobs), dtype=np.float64)
        # Copy rho calculated from one layer of 3D parameter into all layers for
        # current batch of layers
        for layer in range(nlayer_per_batch):
            from_param = layer * nparam_per_layer
            to_param = from_param + nparam_per_layer
            rho_batch[from_param:to_param, :] = rho_one_layer[:, :]
        if DEBUG_PRINT:
            print(f"     {rho_one_layer.shape=}")
            print(f"     {rho_batch.shape=}")

        assert Y.shape[1] == X_batch.shape[1]

        if DEBUG_PRINT:
            print(f"Write rho for the first {nz} observations")
            rho_per_layer_stacked_in_3D_param = np.zeros((nx, ny, nz), dtype=np.float32)
            max_obs_nr = min(nz, nobs)
            for obs_nr in range(max_obs_nr):
                rho_one_layer_one_obs = rho_one_layer[:, obs_nr].reshape((nx, ny))
                rho_per_layer_stacked_in_3D_param[:, :, obs_nr] = rho_one_layer_one_obs[
                    :, :
                ]
            name = "rho_stacked_" + field_param_name
            filename = OUTPUT_PATH + "/" + name + ".roff"
            xtgeo_prop = xtgeo.GridProperty(
                ncol=nx,
                nrow=ny,
                nlay=nz,
                name=name,
                values=rho_per_layer_stacked_in_3D_param,
            )
            print(f"Write file: {filename}")
            xtgeo_prop.to_file(filename, fformat="roff")

            print(f"Write RHO for the next {nz} observations if they exists")
            if nobs > nz:
                max_obs_nr = min(nz, nobs - nz)
            rho_per_layer_stacked_in_3D_param = np.zeros((nx, ny, nz), dtype=np.float32)
            for obs_nr in range(max_obs_nr, nobs):
                rho_one_layer_one_obs = rho_one_layer[:, obs_nr].reshape((nx, ny))
                rho_per_layer_stacked_in_3D_param[:, :, obs_nr - nz] = (
                    rho_one_layer_one_obs[:, :]
                )
            name = "rho_stacked2_" + field_param_name
            filename = OUTPUT_PATH + "/" + name + ".roff"
            xtgeo_prop = xtgeo.GridProperty(
                ncol=nx,
                nrow=ny,
                nlay=nz,
                name=name,
                values=rho_per_layer_stacked_in_3D_param,
            )
            print(f"Write file: {filename}")
            xtgeo_prop.to_file(filename, fformat="roff")

        print(f"     Assimilate batch number {batch_number}")
        X_post_batch = distance_based_esmda_smoother.assimilate_batch(
            X_batch=X_batch, Y=Y, rho_batch=rho_batch
        )
        X_post_group[start:end, :] = X_post_batch[:]

    if nlayer_last_batch > 0:
        batch_number = nbatch
        print(f"     Batch number: {batch_number}")
        start_layer_number = batch_number * nlayer_per_batch
        end_layer_number = start_layer_number + nlayer_last_batch
        start = start_layer_number * nparam_per_layer
        end = end_layer_number * nparam_per_layer
        X_batch = X_group[start:end, :]

        print(f"     Define rho for 3D field {field_param_name}")
        nparam_in_batch = nparam_per_layer * nlayer_last_batch
        rho_batch = np.ones(shape=(nparam_in_batch, nobs), dtype=np.float64)
        if DEBUG_PRINT:
            print(f"     {rho_one_layer.shape=}")
            print(f"     {rho_batch.shape=}")

        # Copy rho calculated from one layer of 3D parameter into all layers for
        # current batch of layers
        for layer in range(nlayer_last_batch):
            from_param = layer * nparam_per_layer
            to_param = from_param + nparam_per_layer
            rho_batch[from_param:to_param, :] = rho_one_layer[:]
        if DEBUG_PRINT:
            print(f"     Define rho for 3D field {field_param_name}")
            print(f"     rho.shape:  {rho_batch.shape}")
        assert Y.shape[1] == X_batch.shape[1]

        print(f"     Assimilate batch number {batch_number}")
        X_post_batch = distance_based_esmda_smoother.assimilate_batch(
            X_batch=X_batch, Y=Y, rho_batch=rho_batch
        )
        X_post_group[start:end, :] = X_post_batch[:]

    return X_group, X_post_group


def update_2D_field_with_distance_esmda(
    distance_based_esmda_smoother,
    field_param_name: str,
    param_config_all,
    X_prior: npt.NDArray[np.double],
    Y: npt.NDArray[np.double],
    obs_xpos: npt.NDArray[np.double],
    obs_ypos: npt.NDArray[np.double],
    obs_main_ranges: npt.NDArray[np.double],
    obs_perp_ranges: npt.NDArray[np.double],
    obs_anisotropy_angle: npt.NDArray[np.double],
) -> list[npt.NDArray[np.double], dict]:
    """
    Calculate posterior update with distance-based ESMDA for one 2D parameter
    The RHO is set to the same for each 2D fields.
    Result is prior and posterior parameter matrices of field parameters for one field.
    """

    surface_coord_dict = {}
    surface_coord_dict["nx"] = param_config_all[field_param_name].ncol
    surface_coord_dict["ny"] = param_config_all[field_param_name].nrow
    yflip = param_config_all[field_param_name].yflip
    surface_coord_dict["yflip"] = yflip
    surface_coord_dict["xinc"] = param_config_all[field_param_name].xinc
    surface_coord_dict["yinc"] = param_config_all[field_param_name].yinc
    surface_coord_dict["xorigo"] = param_config_all[field_param_name].xori
    surface_coord_dict["yorigo"] = param_config_all[field_param_name].yori
    surface_coord_dict["rotation"] = param_config_all[field_param_name].rotation
    # TODO  Workaround due to missing info for param_config for surface
    # Assume origo and rotation point for the 2D map is the same.
    #    surface_coord_dict["xrotationpoint"] = param_config_all[field_param_name].xrot
    #    surface_coord_dict["yrotationpoint"] = param_config_all[field_param_name].yrot
    surface_coord_dict["xrotationpoint"] = surface_coord_dict["xorigo"]
    surface_coord_dict["yrotationpoint"] = surface_coord_dict["yorigo"]

    assert yflip == 1  # TODO Maybe this can be -1  and we need to set yinc to -yinc
    assert surface_coord_dict["yinc"] > 0
    assert surface_coord_dict["xinc"] > 0

    nx = surface_coord_dict["nx"]
    ny = surface_coord_dict["ny"]
    nparam = nx * ny
    nobs = Y.shape[0]
    assert nparam == X_prior.shape[0]
    assert nobs == len(obs_xpos)

    print(
        "  Transform observation position and localization anisotropy angle to "
        "local surface coordinate."
    )
    obs_xpos_transf, obs_ypos_transf, obs_anisotropy_angle_transf = (
        transform_to_local_coordinates_2D(
            surface_coord_dict, obs_xpos, obs_ypos, obs_anisotropy_angle
        )
    )

    print(f"  Define rho for 2D field {field_param_name}")
    if USE_LOCALIZATION:
        rho = calculate_rho_for_summary_obs_for_2D_field(
            surface_coord_dict,
            obs_xpos_transf,
            obs_ypos_transf,
            obs_main_ranges,
            obs_perp_ranges,
            obs_anisotropy_angle_transf,
            scaling_function_name=SCALING_FUNCTION_NAME,
        )
    else:
        rho = np.ones(shape=(nparam, nobs), dtype=np.float64)

    print(f"  Assimilate 2D field parameter {field_param_name}")
    X_post = distance_based_esmda_smoother.assimilate_batch(
        X_batch=X_prior, Y=Y, rho_batch=rho
    )
    return X_post, surface_coord_dict


def write_2D_field_statistics(
    field_param_name: str,
    X_prior: npt.NDArray[np.double],
    X_post: npt.NDArray[np.double],
    surface_coord_dict: dict,
    output_path: str = "TMP",
) -> None:
    # Optionally, calculate mean stdev and write to file
    nx = surface_coord_dict["nx"]
    ny = surface_coord_dict["ny"]
    mean_prior_param = np.mean(X_prior, axis=1).reshape((nx, ny))
    stdev_prior_param = np.std(X_prior, axis=1).reshape((nx, ny))
    mean_post_param = np.mean(X_post, axis=1).reshape((nx, ny))
    stdev_post_param = np.std(X_post, axis=1).reshape((nx, ny))

    filename = output_path + "/" + "local_mean_prior_" + field_param_name + ".irap"
    write_2D_field_param_to_file(filename, surface_coord_dict, mean_prior_param)

    filename = output_path + "/" + "local_std_prior_" + field_param_name + ".irap"
    write_2D_field_param_to_file(filename, surface_coord_dict, stdev_prior_param)

    filename = output_path + "/" + "local_mean_post_" + field_param_name + ".irap"
    write_2D_field_param_to_file(filename, surface_coord_dict, mean_post_param)

    filename = output_path + "/" + "local_std_post_" + field_param_name + ".irap"
    write_2D_field_param_to_file(filename, surface_coord_dict, stdev_post_param)
    print("")


def update_with_distance_esmda_new(
    ensemble,
    realizations,
    param_config_all,
    obs_and_response_df_per_zone_dict: dict,
    obs_and_response_df_for_2D_fields,
    alpha: float,
    seed: int,
    field_params_3D_list_per_zone: dict[str, list[str]],
    field_params_2D_list: list[str],
    ertbox_per_field_param: dict,
    nlayer_per_batch: int,
    scaling_function_name: str,
    truncation: float,
) -> None:
    # dict with group of zones having exactly the same observations
    # and localization settings
    group_of_zones_with_same_obs_dict = define_group_of_zones_with_same_observations(
        obs_and_response_df_per_zone_dict
    )
    if DEBUG_PRINT:
        print(
            "  Group of zones using the same observations and localization parameters:"
        )
        print(f" {json.dumps(group_of_zones_with_same_obs_dict, indent=4)}")

    print("")
    print(" Start update of all 3D field parameters for all zones.")
    previous_ertbox_dict = None
    for zone_group_number, zone_list in group_of_zones_with_same_obs_dict.items():
        print("")
        print(f" Zone group {zone_group_number}")
        print(" List of zones for this group:")
        print(f" {json.dumps(zone_list, indent=4)}")
        first_zone_name_in_group = zone_list[0]
        df_obs_this_zone = obs_and_response_df_per_zone_dict[first_zone_name_in_group]

        # Calculate Y matrix etc
        print(
            " Define response matrix Y and obs vectors and "
            "localization parameter vectors."
        )
        (
            Y,
            observations,
            C_D,
            obs_xpos,
            obs_ypos,
            obs_local_main_ranges,
            obs_local_perp_ranges,
            obs_local_anisotropy_angle,
        ) = define_response_and_observations(ensemble, df_obs_this_zone)
        nobs = Y.shape[0]
        print(
            f" Zones in group {zone_group_number} is conditioned to "
            f"{nobs} observations."
        )

        if DEBUG_PRINT:
            print(f"  Y.shape:  {Y.shape}")
            print(f"  observations.shape:  {observations.shape}")
            print(f"  covariance_obs_error.shape:  {C_D.shape}")

        # All zones in this list use the same set of observations and localization
        # parameters and can use same instance of DistanceESMDA
        print(
            " Initialize DistanceESMDA for 3D fields for zone group number "
            f"{zone_group_number}."
        )
        distance_based_esmda_smoother = DistanceESMDA(
            covariance=C_D, observations=observations, alpha=alpha, seed=seed
        )
        distance_based_esmda_smoother.prepare_assimilation(Y, truncation=truncation)

        for zone_name in zone_list:
            # For current zone all field parameters should have same size
            # and belong to same ERTBOX coordinate system
            print(f"  Zone name: {zone_name}")
            field_param_list_current_zone = field_params_3D_list_per_zone[zone_name]
            print("  Field params for this zone:")
            print(f"  {json.dumps(field_param_list_current_zone, indent=4)}")
            ertbox_dict = ertbox_per_field_param[field_param_list_current_zone[0]]

            # If multiple zones following each other use the same xy layout
            # of the ertbox, which means that all ertbox parameters are
            # equal except for nz, there is no need to transform observations
            # again or re-calculate RHO for one layer
            if previous_ertbox_dict is None or (
                not ertbox_has_same_xy_layout(ertbox_dict, previous_ertbox_dict)
            ):
                # Some of the parameters defining the 2D grid layout of
                # the ERTBOX differs from previous zone.
                # Need to do the coordinate transformation of the observations again.
                nx = ertbox_dict["nx"]
                ny = ertbox_dict["ny"]
                nz = ertbox_dict["nz"]
                nparam_per_layer = nx * ny
                if DEBUG_PRINT:
                    print(f"   Dimension of 3D parameter: ({nx},{ny},{nz})")

                print(
                    "  Transform observation position to local ertbox coordinates "
                    "for this zone"
                )
                (
                    obs_xpos_transformed,
                    obs_ypos_transformed,
                    obs_anisotropy_angle_transformed,
                ) = transform_to_local_coordinates_3D(
                    ertbox_dict, obs_xpos, obs_ypos, obs_local_anisotropy_angle
                )
                # check that transformed points are within the ertbox assuming
                # no obs is outside ertbox area
                xmax = nx * ertbox_dict["xinc"]
                ymax = ny * ertbox_dict["yinc"]
                x_coord_check = np.all(
                    (obs_xpos_transformed >= 0) & (obs_xpos_transformed <= xmax)
                )
                y_coord_check = np.all(
                    (obs_ypos_transformed >= 0) & (obs_ypos_transformed <= ymax)
                )
                if not x_coord_check:
                    raise ValueError(
                        "Some observation points are outside of ertbox in "
                        "local x coordinates"
                    )
                if not y_coord_check:
                    raise ValueError(
                        "Some observation points are outside of ertbox in "
                        "local y coordinates."
                    )

                if USE_LOCALIZATION:
                    print("  Calculate RHO for one layer of field parameter")
                    # Calculate rho for one layer of field parameters.
                    # Localization only calculate lateral distance so
                    # for a 3D parameter
                    # rho(obs_number, field_param(i,j,k1))=rho(obs, field_param(i,j,k2)
                    # for k1, k2 in interval [0, nz-1]
                    # where nz is number of layers for the ERTBOX grid for
                    # the field parameter

                    rho_one_layer = (
                        calculate_rho_for_summary_obs_for_one_layer_of_3D_field(
                            ertbox_dict,
                            obs_xpos_transformed,
                            obs_ypos_transformed,
                            obs_local_main_ranges,
                            obs_local_perp_ranges,
                            obs_anisotropy_angle_transformed,
                            scaling_function_name=scaling_function_name,
                        )
                    )

                    if DEBUG_PRINT:
                        rho_one_layer_old = (
                            calculate_rho_for_summary_obs_for_one_layer_of_3D_field_old(
                                ertbox_dict,
                                obs_xpos_transformed,
                                obs_ypos_transformed,
                                obs_local_main_ranges,
                                obs_local_perp_ranges,
                                obs_anisotropy_angle_transformed,
                                scaling_function_name=scaling_function_name,
                            )
                        )
                        # Check that calculated rho is equal for both functions
                        difference_rho = rho_one_layer_old - rho_one_layer
                        max_diff = np.max(np.abs(difference_rho))
                        print(
                            "   Compare two different calculations of "
                            "RHO for one layer:"
                        )
                        print(f"  {max_diff=}")
                        if max_diff > 0.001:
                            raise ValueError(
                                "Error: RHO calculated by two different functions "
                                "are not equal."
                            )
                        # Write a 3D parameter with nz layers and for the nz first
                        # observations copy rho for one layer into a layer in
                        # this parameter
                        nparam, nobs = rho_one_layer.shape
                        rho_out = np.zeros((nx, ny, nz), dtype=np.float32)
                        # For output to file and to handle handedness correct,
                        # use ertbox grid read from file that is exported from
                        # RMS since the grid know about the handedness.
                        # It is possible to export without refering to the grid object
                        # at all, but then we need to know
                        # about the handedness when creating the property to export.
                        ertbox_grid = xtgeo.grid_from_file(
                            OUTPUT_PATH + "/" + ERTBOX_GRID_FILE_NAME, fformat="roff"
                        )
                        for obs_nr in range(nz):
                            rho_out_flatten_one_obs = rho_one_layer[:, obs_nr]
                            rho_out_2d_one_obs = rho_out_flatten_one_obs.reshape(
                                (nx, ny), order="F"
                            )
                            rho_out[:, :, obs_nr] = rho_out_2d_one_obs[:, :]
                        filename = OUTPUT_PATH + "/rho_per_obs_2D.roff"
                        print(f"Write file: {filename}")
                        rho_xtgeo_property = xtgeo.GridProperty(
                            ncol=nx,
                            nrow=ny,
                            nlay=nz,
                            name="RHO_per_obs",
                            values=rho_out,
                            grid=ertbox_grid,
                        )
                        rho_xtgeo_property.to_file(filename, fformat="roff")
                else:
                    print("   Use RHO equal to 1. No localizaion used.")
                    rho_one_layer = np.ones((nparam_per_layer, nobs), dtype=np.float64)
            else:
                # No need to re-calculate observation coordinates since same xy layout
                # of ERTBOX for this zone as for previous zone,
                # and no need to re-calculate rho for one layer
                pass

            for field_param_name in field_param_list_current_zone:
                print(f"  Field name: {field_param_name} for zone {zone_name}")

                X_prior_group, X_post_group = update_3D_field_with_distance_esmda(
                    distance_based_esmda_smoother,
                    field_param_name,
                    ensemble,
                    realizations,
                    Y,
                    rho_one_layer,
                    nlayer_per_batch,
                    nx,
                    ny,
                    nz,
                )

                # Write updted 3D field parameter to file
                if WRITE_STATS_PARAMS:
                    # Optionally, calculate mean stdev and write to file
                    mean_prior_param = np.mean(X_prior_group, axis=1)
                    stdev_prior_param = np.std(X_prior_group, axis=1)
                    mean_post_param = np.mean(X_post_group, axis=1)
                    stdev_post_param = np.std(X_post_group, axis=1)
                    param_dict = {}
                    key = "local_mean_prior_" + field_param_name
                    param_dict[key] = mean_prior_param

                    key = "local_std_prior_" + field_param_name
                    param_dict[key] = stdev_prior_param

                    key = "local_mean_post_" + field_param_name
                    param_dict[key] = mean_post_param

                    key = "local_std_post_" + field_param_name
                    param_dict[key] = stdev_post_param

                    write_3D_field_param_to_file(
                        param_dict,
                        nx,
                        ny,
                        nz,
                    )
                    print("")

    # Update 2D field parameters:
    print("")
    print("Start Update of all 2D field parameters.")
    print("")
    print(
        " Calculate response matrix Y, observation vector "
        "and localization attribute vectors"
    )
    (
        Y,
        observations,
        C_D,
        obs_xpos,
        obs_ypos,
        obs_main_ranges,
        obs_perp_ranges,
        obs_anisotropy_angle,
    ) = define_response_and_observations(ensemble, obs_and_response_df_for_2D_fields)
    nobs = Y.shape[0]
    print(f" Surfaces are conditioned to {nobs} observations.")
    if DEBUG_PRINT:
        print(f" Y matrix shape for use when updating surfaces:  {Y.shape}")
        print(
            f" Observations fshape or use when updating surfaces:  {observations.shape}"
        )

    # Initialize smoother again for this set of observations and observation error
    distance_based_esmda_smoother = DistanceESMDA(
        covariance=C_D, observations=observations, alpha=alpha, seed=seed
    )
    distance_based_esmda_smoother.prepare_assimilation(Y, truncation=truncation)

    for surface_name in field_params_2D_list:
        print(f"  Surface field: {surface_name}")
        X_prior_group = ensemble.load_parameters_numpy(surface_name, realizations)
        X_post_group, surface_coord_dict = update_2D_field_with_distance_esmda(
            distance_based_esmda_smoother,
            surface_name,
            param_config_all,
            X_prior_group,
            Y,
            obs_xpos,
            obs_ypos,
            obs_main_ranges,
            obs_perp_ranges,
            obs_anisotropy_angle,
        )
        if WRITE_STATS_PARAMS:
            print("  Calculate statistics and write 2D field params to file")
            write_2D_field_statistics(
                surface_name,
                X_prior_group,
                X_post_group,
                surface_coord_dict,
                output_path=OUTPUT_PATH,
            )


def get_data_frame_with_observations_for_2D_fields(obs_data_frame) -> pl.DataFrame:
    # Add a new column for the product of main_range and perp_range
    if not isinstance(obs_data_frame, pl.DataFrame):
        raise TypeError("Input data must be a Polars DataFrame.")

    print(f"{obs_data_frame.shape}")
    df = obs_data_frame.with_columns(
        (pl.col("main_range") * pl.col("perp_range")).alias("influence_area")
    )
    #    print(df.columns)
    # Group by 'observation_key' and select the line with the largest 'influence_area'
    # result_df = df.group_by("observation_key",maintain_order=True)
    result_df = df.group_by("observation_key", maintain_order=True).agg(
        pl.all().sort_by("influence_area", descending=True).first()
    )
    print("result.shape")
    #    print(result_df)
    return result_df


def split_observations_into_one_dataframe_per_zone(
    df_obs, input_zone_names: list[str]
) -> dict[str, pl.DataFrame]:
    defined_zone_names = copy.copy(input_zone_names)
    defined_zone_names.sort()

    # Compute `influence_area` column
    df = df_obs.with_columns(
        (pl.col("main_range") * pl.col("perp_range")).alias("influence_area")
    )

    # Split the DataFrame into one DataFrame per `zone_name`
    # Get a list of the zone names
    zone_names = df["zone_name"].unique().to_list()
    zone_names.sort()
    if zone_names != defined_zone_names:
        raise ValueError(
            f"Zone names defined for observations: {zone_names} \n"
            f"and zone names defined for the ERT model:  {defined_zone_names}\n"
            "are different."
        )

    # Create a dictionary to store the DataFrames per zone_name
    zone_dataframes = {
        zone: df.filter(pl.col("zone_name") == zone) for zone in zone_names
    }

    # Check if observation_key values are unique per zone
    for zone_name, df in zone_dataframes.items():
        has_no_duplicated_obs, list_of_duplicated_obs = check_unique_observation_key(df)
        if not has_no_duplicated_obs:
            print("Duplicated observation:")
            print(f" {list_of_duplicated_obs}")
            raise ValueError(
                "Duplicated observations found in "
                f"observation dataframe for zone {zone_name}"
            )
    return zone_dataframes


def check_unique_observation_key(df: pl.DataFrame) -> tuple[bool, list]:
    # Group by "observation_key" and count the occurrences
    counts = df.group_by("observation_key").len()
    #    print(f"{counts=}")
    # Find rows where count > 1 (i.e., non-unique values)
    non_unique = counts.filter(counts["len"] > 1)

    # Extract the non-unique keys as a list
    non_unique_keys = non_unique["observation_key"].to_list()

    # Return True if all keys are unique, otherwise False
    # with the list of non-unique values
    return len(non_unique_keys) == 0, non_unique_keys


def define_observations_for_2D_fields(df_per_zone: dict) -> pl.DataFrame:
    # List of all input DataFrames
    dataframe_list = [df_per_zone[zone_name] for zone_name in list(df_per_zone.keys())]
    df1 = dataframe_list[0]
    # Concatenate all DataFrames into one with an identifier for the source
    combined_df = pl.concat(dataframe_list)

    # Group by "observation_key" and select the row with the max "influence_area"
    # per group
    result_df = (
        combined_df.sort(
            "influence_area", descending=True
        )  # Sort by "influence_area" in descending order
        .group_by("observation_key")
        .agg(pl.col("*").first())  # Select the first row per group after sorting
    )

    # Ensure the result DataFrame has exactly the same columns as the input DataFrames
    result_df = result_df.select(df1.columns)
    return result_df


def ertbox_has_same_xy_layout(ertbox1_dict: dict, ertbox2_dict: dict) -> bool:
    """
    Check if two different ertbox dict has same xy layout.
    Return True of same, False if not same.
    Parameter nz and zinc is irrelevant here.
    Handedness must be the same to get the same order of the field values.
    """
    if (
        (ertbox1_dict["xorigo"] == ertbox2_dict["xorigo"])
        and (ertbox1_dict["yorigo"] == ertbox2_dict["yorigo"])
        and (ertbox1_dict["xinc"] == ertbox2_dict["xinc"])
        and (ertbox1_dict["yinc"] == ertbox2_dict["yinc"])
        and (ertbox1_dict["rotation"] == ertbox2_dict["rotation"])
        and (ertbox1_dict["nx"] == ertbox2_dict["nx"])
        and (ertbox1_dict["ny"] == ertbox2_dict["ny"])
        and (ertbox1_dict["handedness"] == ertbox2_dict["handedness"])
    ):
        return True
    return False


def define_group_of_zones_with_same_observations(
    observation_df_per_zone: dict[str, pl.DataFrame],
) -> dict[int, list[str]]:
    # Create the output dictionary
    obs_group_dict = {}
    group_number = 1
    processed_zones = set()

    # Compare all DataFrames
    for zone_name, df in observation_df_per_zone.items():
        if zone_name in processed_zones:
            continue  # Skip already grouped zones

        # Initialize a new group for this zone
        identical_zones = [zone_name]

        # Compare this DataFrame with all others
        for other_zone_name, other_df in observation_df_per_zone.items():
            if other_zone_name != zone_name and other_zone_name not in processed_zones:
                if df.equals(other_df):
                    identical_zones.append(other_zone_name)

        # Assign this group to the output dictionary
        obs_group_dict[group_number] = identical_zones
        group_number += 1

        # Mark all zones in this group as processed
        processed_zones.update(identical_zones)

    # Print the resulting dictionary

    return obs_group_dict


def test_transform_coordinates():
    n = 4
    ertbox_dict = ERTBOX_PER_3D_FIELD_PARAM_GROUP["aps_Valysar_GRF1"]
    xpos = np.zeros(n, dtype=np.float64)
    ypos = np.zeros(n, dtype=np.float64)
    angle = np.zeros(n, dtype=np.float64)

    # Lower left corner
    xpos[0] = ertbox_dict["xorigo"]
    ypos[0] = ertbox_dict["yorigo"]
    angle[0] = ROTATION

    # Upper left corner
    xpos[1] = 456070
    ypos[1] = 5935985
    angle[1] = ROTATION + 90.0

    # Upper right corner
    xpos[2] = 462062
    ypos[2] = 5939430
    angle[2] = 0.0

    # Lower right corner
    xpos[3] = 467497
    ypos[3] = 5929973
    angle[3] = 0.0

    # ERTBOX coordinates
    xpos_transf, ypos_transf, angle_transf = transform_to_local_coordinates_3D(
        ertbox_dict, xpos, ypos, angle
    )
    print("Transformed coordinates into ERTBOX coordinates for test points:")
    for i in range(n):
        print(f"{i}  {xpos_transf[i]}, {ypos_transf[i]}, {angle_transf[i]}")

    print("")
    #
    with open_storage(STORAGE_PATH, "r") as storage:
        experiment = storage.get_experiment_by_name(EXPERIMENT_NAME)
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())
        surface_field_names = get_2D_field_parameter_names(groups, param_config_all)
        for group_name in groups:
            if group_name in surface_field_names:
                surf_config = param_config_all[group_name]
                print("")
                print(group_name)
                print(f"{surf_config=}")
                yflip = surf_config.yflip

                surface_coord_dict = {
                    "name": surf_config.name,
                    "nx": surf_config.ncol,
                    "ny": surf_config.nrow,
                    "yflip": yflip,
                    "xorigo": surf_config.xori,
                    "yorigo": surf_config.yori,
                    "xinc": surf_config.xinc,
                    "yinc": surf_config.yinc,
                    "rotation": surf_config.rotation,
                    "xrotationpoint": surf_config.xori,
                    "yrotationpoint": surf_config.yori,
                }
                # Local surface coordinates
                print(f" {json.dumps(surface_coord_dict, indent=4)}")
                xpos_transf, ypos_transf, angle_transf = (
                    transform_to_local_coordinates_2D(
                        surface_coord_dict, xpos, ypos, angle
                    )
                )
                print(
                    "Transformed coordinates into surface coordinates for test points:"
                )
                for i in range(n):
                    print(f"{i}  {xpos_transf[i]}, {ypos_transf[i]}, {angle_transf[i]}")


def test_calc_rho_one_layer():
    ertbox_dict = {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "xinc": XINC,
        "yinc": YINC,
        "rotation": ROTATION,
        "nx": NX,
        "ny": NY,
        "nz": NZ,
        "handedness": HANDEDNESS,
    }
    xsize = ertbox_dict["xinc"] * ertbox_dict["nx"]
    ysize = ertbox_dict["yinc"] * ertbox_dict["ny"]
    ertbox_dict
    nobs = 4
    obs_xpos = np.zeros(nobs, dtype=np.float64)
    obs_ypos = np.zeros(nobs, dtype=np.float64)
    obs_perp_range = np.zeros(nobs, dtype=np.float64)
    obs_main_range = np.zeros(nobs, dtype=np.float64)
    obs_anisotropy_angle = np.zeros(nobs, dtype=np.float64)

    obs_xpos[0] = xsize / 2
    obs_ypos[0] = ysize / 2
    obs_anisotropy_angle[0] = 45.0
    obs_main_range[0] = 1500
    obs_perp_range[0] = 1250

    obs_xpos[1] = xsize
    obs_ypos[1] = 0
    obs_anisotropy_angle[1] = -45.0
    obs_main_range[1] = xsize
    obs_perp_range[1] = xsize / 10

    obs_xpos[2] = 0
    obs_ypos[2] = ysize
    obs_anisotropy_angle[2] = -45.0
    obs_main_range[2] = xsize
    obs_perp_range[2] = xsize / 10

    obs_xpos[3] = xsize
    obs_ypos[3] = ysize
    obs_anisotropy_angle[3] = 45.0
    obs_main_range[3] = xsize
    obs_perp_range[3] = xsize / 10

    rho_one_layer = calculate_rho_for_summary_obs_for_one_layer_of_3D_field(
        ertbox_dict,
        obs_xpos,
        obs_ypos,
        obs_main_range,
        obs_perp_range,
        obs_anisotropy_angle,
        scaling_function_name="gaussian",
    )
    print(f"{rho_one_layer.shape=}")
    #    print(f"{rho_one_layer=}")
    nx = ertbox_dict["nx"]
    ny = ertbox_dict["ny"]
    nz = ertbox_dict["nz"]
    values3d = np.zeros((nx, ny, nz), dtype=np.float32)
    for n in range(nobs):
        name = "rho_" + str(n)
        rho_2d = rho_one_layer[:, n].reshape((nx, ny), order="F")
        for k in range(nz):
            values3d[:, :, k] = rho_2d[:, :]
        rho_property = xtgeo.GridProperty(
            ncol=nx, nrow=ny, nlay=nz, name="rho", values=values3d
        )
        filename = name + ".roff"
        print(f"Write file: {filename}")
        rho_property.to_file(filename, fformat="roff", name=name)


def main():
    # Number of rows to print from polars dataframe
    Nmax_rows = 500
    Nmax_cols = 15
    pl.Config.set_tbl_rows(Nmax_rows)
    pl.Config.set_tbl_cols(Nmax_cols)
    if TESTS:
        import sys

        test_transform_coordinates()
        test_calc_rho_one_layer()
        sys.exit(0)

    if DEBUG_PRINT:
        with open_storage(STORAGE_PATH) as storage:
            [
                print(f"Available experiment names: {x.name}")
                for x in storage.experiments
            ]
            print("")

    print("Step 1: Get ensemble and observations from storage")
    with open_storage(STORAGE_PATH, "r") as storage:
        experiment = storage.get_experiment_by_name(EXPERIMENT_NAME)
        ensemble = experiment.get_ensemble_by_name(ENSEMBLE_NAME)
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())
        realizations = ensemble.get_realization_list_with_responses()
        selected_obs = ensemble.experiment.observation_keys
        iens_active_index = np.array(ensemble.get_realization_list_with_responses())
        observations_and_responses = ensemble.get_observations_and_responses(
            selected_obs, iens_active_index
        )

        print(
            "Step 2: Get observations with position and localization"
            " parameters from file generated by an RMS script."
        )
        df_obs_with_local = read_observations_with_localization_attributes(
            OBS_SUMMARY_WITH_LOCAL_ATTRIBUTES_FILE
        )

        print(
            "Step 3: Combine the observation dataframe from storage with "
            "the observation data frame from file with additional information "
            "about position and localization attributes per observation"
        )
        df_obs_merged = observations_and_responses.join(
            df_obs_with_local, on="observation_key", how="inner"
        )

        if DEBUG_PRINT:
            columns_to_print = [
                "observation_key",
                "observations",
                "value",
                "xpos",
                "ypos",
                "main_range",
                "perp_range",
                "anisotropy_angle",
                "zone_name",
            ]
            selected_columns = [
                col for col in df_obs_merged.columns if col in columns_to_print
            ]
            print("Selected columns:")
            print(df_obs_merged.select(selected_columns))
            print("")

        print("Step 4: Split observations into one set per zone")
        # dict with observation dataframe per zone
        df_obs_per_zone_dict = split_observations_into_one_dataframe_per_zone(
            df_obs_merged, ZONES
        )
        if DEBUG_PRINT:
            print(f"{df_obs_per_zone_dict=}")

        print(
            "Step 5: Define a dataframe for 2D field parameters where the largest "
            "influence range per summary observation is used as "
            "localization parameters."
        )
        # observation dataframe to be used for 2D fields
        df_obs_for_2D_fields = define_observations_for_2D_fields(df_obs_per_zone_dict)
        if DEBUG_PRINT:
            print(df_obs_for_2D_fields)

        print("Step 6: Get list of 3D field parameters if any.")
        # dict with zone name as key and value that is a list of
        # 3D field parameter names
        field_param_3d_list_per_zone_dict = get_3D_field_parameter_names_per_zone(
            groups, param_config_all, ZONE_PER_3D_FIELD_PARAM_GROUP
        )
        if DEBUG_PRINT:
            print(" Dict of 3D field parameters:")
            print(f" {json.dumps(field_param_3d_list_per_zone_dict, indent=4)}")

        print("Step 7: Get list of 2D field parameters if any.")
        field_param_2d_list = get_2D_field_parameter_names(groups, param_config_all)
        if DEBUG_PRINT:
            print(" List of 2D field parameters:")
            print(f" {json.dumps(field_param_2d_list, indent=4)}")

        print("Step 8: Run update with DistanceESMDA")
        update_with_distance_esmda_new(
            ensemble,
            realizations,
            param_config_all,
            df_obs_per_zone_dict,
            df_obs_for_2D_fields,
            ALPHA,
            SEED,
            field_param_3d_list_per_zone_dict,
            field_param_2d_list,
            ERTBOX_PER_3D_FIELD_PARAM_GROUP,
            NLAYER_PER_BATCH,
            SCALING_FUNCTION_NAME,
            TRUNCATION,
        )


# --- main ---
if __name__ == "__main__":
    #    calculate_rho_for_summary_obs_for_one_layer_of_3D_field = \
    #     monitor_performance(calculate_rho_for_summary_obs_for_one_layer_of_3D_field)
    #    calculate_rho_for_summary_obs_for_2D_field = \
    #     monitor_performance(calculate_rho_for_summary_obs_for_2D_field)
    #    update_3D_field_with_distance_esmda = \
    #     monitor_performance(update_3D_field_with_distance_esmda)
    #    update_2D_field_with_distance_esmda = \
    #     monitor_performance(update_2D_field_with_distance_esmda)
    update_with_esmda = monitor_performance(update_with_esmda)
    update_with_distance_esmda_new = monitor_performance(update_with_distance_esmda_new)
    main()
