#!/usr/bin/env python
# coding: utf-8

# # Test Distance Based Localization on real cases


import time

import numpy as np
import polars as pl
import xtgeo
from ert.storage import open_storage

from iterative_ensemble_smoother.esmda import ESMDA
from iterative_ensemble_smoother.experimental import DistanceESMDA

STORAGE_PATH = (
    "/project/fmu/users/olia/drogon_20250623_11-50/"
    "resmod/ff/25.0.0/ert/output/drogon_ahm/storage"
)

SEED = 42
ALPHA = 1
NLAYER_PER_BATCH = (
    40  # 66 layers in ERTBOX for Drogon which is split into 3 batches here
)
USE_LOCALIZATION = False
WRITE_STATS_PARAMS = True

XORIGO = 456063.69091796875
YORIGO = 5935990.898925781
XINC = 75.17192661654963
YINC = 74.79699019286826
ROTATION = 29.88159640627248
NX = 92
NY = 146
NZ = 66

# WellObs - Observations from wells with position (prod data etc)"
# GenObs  - Any observation having a location like seismic obs points,
#           gravimetry obs points
# RegionObs - Any observation without any specific coordinate for
#             its location (e.g. region or field prod data,
#             data for average over regions, FWL, GOC which are
#             defined per region)
OBS_TYPES_WITH_LOCATION = ["WellObs", "GenObs"]
OBS_TYPES_WITHOUT_LOCATION = ["RegionObs"]

OBS_FILE_PATH = (
    "/project/fmu/users/olia/drogon_20250623_11-50/resmod/ff/25.0.0/rms/model/"
)
SUMMAY_FILE = "summary_obs.csv"
LOCAL_ATTRIBUTE_FILE = "localisation_obs_attributes.csv"
OBS_SUMMARY_FILE = OBS_FILE_PATH + SUMMAY_FILE
OBS_LOCAL_ATTRIBUTE_FILE = OBS_FILE_PATH + LOCAL_ATTRIBUTE_FILE


def define_field_param_grid_dict(
    xorigo: float,
    yorigo: float,
    rotation: float,
    xinc: float,
    yinc: float,
    nx: int,
    ny: int,
    nz: int,
) -> dict:
    return {
        "xorigo": xorigo,
        "yorigo": yorigo,
        "rotation": rotation,
        "xinc": xinc,
        "yinc": yinc,
        "nx": nx,
        "ny": ny,
        "nz": nz,
    }


def read_obs_and_localization_range_files(
    summary_obs_file: str, well_localization_attributes_file: str
) -> list[dict]:
    """
    Read info about observations and localization parameters from files generated by
    the script
    """
    print(f"Read file: {summary_obs_file}")
    with open(summary_obs_file, "r") as file:
        line_list = file.readlines()
    obs_list = []
    read_headings = False
    for line in line_list:
        if len(line) == 0:
            continue
        # Assume first non-empty line in the file contains the headings
        if not read_headings:
            read_headings = True
            headings = line.split()
            headings = [heading.strip().lower() for heading in headings]
            continue
        words = line.split()
        record = {}
        for index, heading in enumerate(headings):
            if heading in ["summary_key", "date", "zone"]:
                value = str(words[index].strip())
            else:
                value = float(words[index].strip())
            record[heading] = value
        obs_list.append(record)

    print(f"Read file: {well_localization_attributes_file}")
    with open(well_localization_attributes_file, "r") as file:
        line_list = file.readlines()
    read_headings = False
    obs_localization_attribute_list = []
    for line in line_list:
        if len(line) == 0:
            continue
        # Assume first non-empty line in the file contains the headings
        if not read_headings:
            read_headings = True
            headings = line.split()
            headings = [heading.strip().lower() for heading in headings]
            continue
        words = line.split()
        record = {}
        for index, heading in enumerate(headings):
            if heading in ["summary_key", "zone"]:
                value = str(words[index].strip())
            else:
                value = float(words[index].strip())
            record[heading] = value
        obs_localization_attribute_list.append(record)

    # Merge together attributes with observations
    for obs_dict in obs_list:
        for obs_attribute_dict in obs_localization_attribute_list:
            if (
                obs_dict["summary_key"] == obs_attribute_dict["summary_key"]
                and obs_dict["zone"] == obs_attribute_dict["zone"]
            ):
            #    print("")
            #    print(f"Obs dict before: {obs_dict=}")
            #    print(f"Obs attribute: {obs_attribute_dict=}")
                obs_dict["xpos"] = obs_attribute_dict["xpos"]
                obs_dict["ypos"] = obs_attribute_dict["ypos"]
                obs_dict["main_range"] = obs_attribute_dict["main_range"]
                obs_dict["perp_range"] = obs_attribute_dict["perp_range"]
                obs_dict["azimuth"] = obs_attribute_dict["azimuth"]
                obs_dict["zone"] = obs_attribute_dict["zone"]
                break
        print(f"Obs dict after: {obs_dict=}")
    return obs_list


def monitor_performance(func):
    """Decorator to monitor time only"""

    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()

        result = func(*args, **kwargs)

        end_time = time.perf_counter()

        print(f"Function {func.__name__}:")
        print(f"  Total time: {end_time - start_time:.2f}s")

        return result

    return wrapper


def update_with_esmda(
    storage,
    storage_path: str,
    experiment_name: str,
    ensemble_name: str,
    observations: np.ndarray,
    C_D: np.ndarray,
    Y: np.ndarray,
    ensemble_size: int,
    n_param_per_group: np.ndarray,
    groups_with_3d_fields: list[str],
    groups_with_2d_fields: list[str],
    groups_with_scalars: list[str],
    seed: int = 42,
    alpha: int = 1,
    write_stats_params: bool = True,
) -> list[dict[str, np.ndarray], dict[str, np.ndarray], int, int, int]:
    # Initialize ESMDA
    print(f"Initialize ESMDA for alpha = {alpha}")
    # Workaround to ensure ESMDA don't fail when repeating call on assimilate
    alpha_workaround = np.zeros((1000), dtype=np.float32)
    alpha_workaround[:] = 1.0
    smoother_ESMDA = ESMDA(
        covariance=C_D, observations=observations, alpha=alpha_workaround, seed=seed
    )
    #    print(f"{observations=}")
    # print(f"Perturb observations for ESMDA")
    # D = smoother_ESMDA.perturb_observations(
    #    ensemble_size=ensemble_size, alpha=alpha
    # )

    print("Loop over all parameter groups and update with ESMDA")
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    X_prior_dict = {}
    X_posterior_dict = {}
    print(f"{n_param_per_group=}")
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name(ensemble_name)
        # ensemble = experiment.get_ensemble_by_name("ensemble")
        # groups = list(experiment.parameter_configuration.keys())
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())

        realizations = ensemble.get_realization_list_with_responses()
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f" Skip group {group_name} which cannot be updated")
                continue

            print(
                f"Process parameter group: {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            if group_name in groups_with_3d_fields:
                print(f" Parameter group {group_name} is a 3D field")
                param_type = "3D"
                nx = param_config_all[group_name].nx
                ny = param_config_all[group_name].ny
                nz = param_config_all[group_name].nz
            elif group_name in groups_with_2d_fields:
                print(f" Parameter group {group_name} is a 2D field")
                param_type = "2D"
                nx, ny, nz = 0, 0, 0
                nx = param_config_all[group_name].ncol
                ny = param_config_all[group_name].nrow
                nz = 1
            elif group_name in groups_with_scalars:
                param_type = "Scalar"
                nx, ny, nz = 0, 0, 0
            else:
                print(
                    f" Warning: {group_name} is of unknown type. Will not be updated."
                )
                continue

            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            print(f"X_group.shape = {X_group.shape}")
            print(f"Y.shape = {Y.shape}")
            assert Y.shape[1] == X_group.shape[1]

            print(" Assimilate")
            X_post_group = smoother_ESMDA.assimilate(X=X_group, Y=Y)
            X_posterior_dict[group_name] = X_post_group
            X_prior_dict[group_name] = X_group

            print(
                f"Complete ESMDA for parameter group {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            print("")
            group_number += 1

            if write_stats_params and param_type == "3D":
                # Optionally, calculate mean stdev and write to file
                mean_prior_param = np.mean(X_group, axis=1)
                stdev_prior_param = np.std(X_group, axis=1)

                mean_post_param = np.mean(X_post_group, axis=1)
                stdev_post_param = np.std(X_post_group, axis=1)
                param_dict = {}
                key = "global_mean_prior_" + group_name
                param_dict[key] = mean_prior_param

                key = "global_std_prior_" + group_name
                param_dict[key] = stdev_prior_param

                key = "global_mean_post_" + group_name
                param_dict[key] = mean_post_param

                key = "global_std_post_" + group_name
                param_dict[key] = stdev_post_param

                write_3d_field_param_to_file(param_dict, nx, ny, nz)
                print("")
    return [X_prior_dict, X_posterior_dict, param_type, nx, ny, nz]


def update_with_distance_esmda(
    storage,
    storage_path: str,
    experiment_name: str,
    ensemble_name: str,
    observations: np.ndarray,
    C_D: np.ndarray,
    Y: np.ndarray,
    n_param_per_group: np.ndarray,
    groups_with_3d_fields: list[str],
    groups_with_2d_fields: list[str],
    groups_with_scalars: list[str],
    seed: int = 42,
    alpha: int = 1,
    nlayer_per_batch: int = 22,
    write_stats_params: bool = True,
    use_localization: bool = False,
) -> list[dict[str, np.ndarray], int, int, int]:
    # ## Ensemble Smoother with Distance Based Localization

    print("")
    print("Start initialize DistanceESMDA")
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    smoother = DistanceESMDA(
        covariance=C_D, observations=observations, alpha=alpha, seed=seed
    )
    smoother.prepare_assimilation(Y, truncation=0.99)

    print("Loop over all parameter groups and update with DistanceESMDA")
    X_posterior_dict = {}
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name(ensemble_name)
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())
        realizations = ensemble.get_realization_list_with_responses()
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f" Skip group {group_name} which cannot be updated")
                continue
            print(
                f"Process parameter group: {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            nparam, nreal = X_group.shape
            X_post_group = np.zeros((nparam, nreal), dtype=np.float32)
            if group_name in groups_with_3d_fields:
                print(f" Parameter group {group_name} is a 3D field")
                param_type = "3D"
                nx = param_config_all[group_name].nx
                ny = param_config_all[group_name].ny
                nz = param_config_all[group_name].nz

                print(f" Dimension of 3D parameter: ({nx},{ny},{nz})")

                nbatch = int(nz / nlayer_per_batch)
                nlayer_last_batch = nz - nbatch * nlayer_per_batch
                for batch_number in range(nbatch):
                    start_layer_number = batch_number * nlayer_per_batch
                    end_layer_number = start_layer_number + nlayer_per_batch
                    start = start_layer_number * nx * ny
                    end = end_layer_number * nx * ny
                    X_batch = X_group[start:end, :]

                    print(f" Define rho for 3D field {group_name}")
                    nparam_in_batch = nx * ny * nlayer_per_batch

                    if not use_localization:
                        # rho = 1 without localization
                        rho = np.ones(shape=(nparam_in_batch, Y.shape[0]))  # temporary
                    print(f" rho.shape:  {rho.shape}")
                    assert Y.shape[1] == X_batch.shape[1]

                    print(f" Assimilate batch number {batch_number}")
                    X_post_batch = smoother.assimilate_batch(
                        X_batch=X_batch, Y=Y, rho_batch=rho
                    )
                    X_post_group[start:end, :] = X_post_batch[:]

                if nlayer_last_batch > 0:
                    batch_number = nbatch
                    start_layer_number = batch_number * nlayer_per_batch
                    end_layer_number = start_layer_number + nlayer_last_batch
                    start = start_layer_number * nx * ny
                    end = end_layer_number * nx * ny
                    X_batch = X_group[start:end, :]

                    print(f" Define rho for 3D field {group_name}")
                    nparam_in_batch = nx * ny * nlayer_last_batch
                    rho = np.ones(shape=(nparam_in_batch, Y.shape[0]))  # temporary
                    print(f" rho.shape:  {rho.shape}")
                    assert Y.shape[1] == X_batch.shape[1]

                    print(f" Assimilate batch number {batch_number}")
                    X_post_batch = smoother.assimilate_batch(
                        X_batch=X_batch, Y=Y, rho_batch=rho
                    )
                    X_post_group[start:end, :] = X_post_batch[:]

            elif group_name in groups_with_2d_fields:
                print(f" Parameter group {group_name} is a 2D field")
                param_type = "2D"
                nx = param_config_all[group_name].ncol
                ny = param_config_all[group_name].nrow
                nz = 1
                print(f" Define rho for 2D field {group_name}")
                rho = np.ones(shape=(X_group.shape[0], Y.shape[0]))  # temporary
                print(f" rho.shape:  {rho.shape}")

                X_group = ensemble.load_parameters_numpy(group_name, realizations)
                assert Y.shape[1] == X_group.shape[1]
                print(" Assimilate")
                X_post_group = smoother.assimilate_batch(
                    X_batch=X_group, Y=Y, rho_batch=rho
                )

            elif group_name in groups_with_scalars:
                param_type = "Scalar"
                nx, ny, nz = 0, 0, 0
                X_post_group = None
                print(
                    f" Skip scalar parameter group {group_name} "
                    "in distance-based localization"
                )
            else:
                print(
                    f" Warning: {group_name} is of unknown type. Will not be updated."
                )
                continue

            X_posterior_dict[group_name] = [X_post_group, param_type, nx, ny, nz]

            print(
                f"Complete DistanceESMDA for parameter group {group_name} "
                f"with {n_param_per_group[group_number]} parameters"
            )
            print("")
            group_number += 1

            if write_stats_params and param_type == "3D":
                # Optionally, calculate mean stdev and write to file
                mean_post_param = np.mean(X_post_group, axis=1)
                stdev_post_param = np.std(X_post_group, axis=1)
                param_dict = {}

                key = "local_mean_post_" + group_name
                param_dict[key] = mean_post_param

                key = "local_std_post_" + group_name
                param_dict[key] = stdev_post_param

                write_3d_field_param_to_file(param_dict, nx, ny, nz)
                print("")
    return [X_posterior_dict, param_type, nx, ny, nz]


def define_response_and_observations(
    ensemble,
    observations_and_responses,
):
    response_cols = [
        str(i) for i in range(1, ensemble.ensemble_size)
    ]  # Why from 1 and not 0?
    # response_cols = [str(i) for i in range(0, ensemble.ensemble_size)]
    df_filtered = observations_and_responses.filter(
        pl.concat_list([pl.col(col) for col in response_cols])
        .list.eval(pl.element().std())
        .list.first()
        > 0
    )
    # print(df_filtered)

    Y = df_filtered.select(
        pl.all().exclude(
            ["response_key", "index", "observation_key", "observations", "std"]
        )
    ).to_numpy()

    observations = df_filtered["observations"].to_numpy()
    std = df_filtered["std"].to_numpy()
    C_D = std**2

    return Y, observations, C_D


def write_3d_field_param_to_file(
    param_dict: dict[str, np.ndarray],
    nx: int,
    ny: int,
    nz: int,
    output_path: str = "TMP",
) -> None:
    """
    Write 3D parameter to ROFF format file to be readable by RMS
    """
    for param_name, values in param_dict.items():
        xtgeo_param = xtgeo.GridProperty(
            ncol=nx, nrow=ny, nlay=nz, name=param_name, values=values
        )
        file_name = output_path + "/" + param_name + ".roff"
        print(f"Write file: {file_name}")
        xtgeo_param.to_file(file_name, fformat="roff")


def calculate_rho_for_one_layer_of_3d_field(
    ertbox_dict: dict,
    obs_list: list,
):
    """
    Input:
    Specification of ERTBOX for the field
    (xorigo, yorigo,rotation,xinc,yinc,nx,ny,nz)
    For each observation, position, localization range
    (rotated to the local coordinate system defined by ERTBOX)
    type of observation (well observation, seismic observation,
    other observation types without position) scaling function (tapering function)
    for each observation for current field parameters

    Output: rho for one layer with nx * ny field parameter values for all observations
    having position.
    """
    # Center points of each grid cell in field parameter grid
    # in local coordinate system (ertbox grid)
    x_local = np.arange(ertbox_dict.nx)
    x_local = (x_local + 0.5) * ertbox_dict.xinc
    y_local = np.arange(ertbox_dict.ny)
    y_local = (y_local + 0.5) * ertbox_dict.yinc
    mesh_y_local, mesh_x_coord = np.meshgrid(y_local, x_local, indexing="ij")
    # for obs_nr, obs
    # #for obs_nr, obs_pos
    # #for obs_pos in observation_positions:
    # dX = grid_x_coord - obs_xpos
    # dY = grid_y_coord - obs_ypos
    # rotation = ellipse_rotation * np.pi / 180.0
    # cosangle = math.cos(rotation)
    # sinangle = math.sin(rotation)
    # #    print(f"shape of dX: {dX.shape} ")
    # #    print(f"shape of dY: {dY.shape} ")
    # dX_ellipse = (dX * cosangle + dY * sinangle) / main_range
    # dY_ellipse = (-dX * sinangle + dY * cosangle) / perp_range
    # distances_2d = np.sqrt(dX_ellipse * dX_ellipse + dY_ellipse * dY_ellipse)
    # distances = distances_2d.flatten()
    # scaling_factors = scaling_function(distances)


def get_number_of_groups_and_parameters(
    storage_path: str, experiment_name: str, groups_updatable: list[str]
) -> list[int, list[int]]:
    n_param_total = 0
    n_param_per_group = []
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name("ensemble")
        groups = list(experiment.parameter_configuration.keys())
        realizations = ensemble.get_realization_list_with_responses()
        assert ensemble.ensemble_size == len(realizations)
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f"Skip group {group_name} which cannot be updated")
                continue

            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            nparam = X_group.shape[0]
            n_param_total += nparam
            n_param_per_group.append(nparam)
            print(
                f" Number of param in group {group_number}"
                f" with name {group_name} is {nparam}"
            )
            group_number += 1
    return n_param_total, n_param_per_group


def main():
    with open_storage(STORAGE_PATH) as storage:
        [print(f"Available experiment names: {x.name}") for x in storage.experiments]

    # ## Pick which experiment to analyse
    experiment_name = "ensemble_experiment"
    ensemble_name = "ensemble"

    # Load observations and responses from storage.
    # Remove responses with zero standard deviation
    print("Get observations and responses")
    with open_storage(STORAGE_PATH, "r") as storage:
        ensemble = storage.get_experiment_by_name(experiment_name).get_ensemble_by_name(
            "ensemble"
        )
        ensemble_size = ensemble.ensemble_size
        selected_obs = ensemble.experiment.observation_keys
        iens_active_index = np.array(ensemble.get_realization_list_with_responses())
        observations_and_responses = ensemble.get_observations_and_responses(
            selected_obs, iens_active_index
        )
        print(observations_and_responses.glimpse(return_as_string=True))

    obs_list = read_obs_and_localization_range_files(
        OBS_SUMMARY_FILE, OBS_LOCAL_ATTRIBUTE_FILE
    )

    # Define type of parameter (scalars, 2D, 3D parameter)
    # skip_groups = ["SWITCHES", "DESIGN_MATRIX"]
    groups_with_3d_fields = [
        "aps_Valysar_GRF1",
        "aps_Valysar_GRF2",
        "aps_Valysar_GRF3",
        "aps_Therys_GRF1",
        "aps_Therys_GRF2",
        "aps_Therys_GRF3",
        "aps_Volon_GRF1",
        "aps_Volon_GRF2",
        "aps_Volon_GRF3",
    ]
    groups_with_2d_fields = [
        "TOP_VOLANTIS",
        "TOP_THERYS",
        "TOP_VOLON",
        "BASE_VOLANTIS",
    ]
    groups_with_scalars = [
        "GLOBVAR",
        "MULTREGT",
        "RATE",
    ]
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    # print(f"{groups_updatable=}")
    print(
        "Get number of updatable parameter groups "
        "and number of parameters per updatable group"
    )
    n_param_total, n_param_per_group = get_number_of_groups_and_parameters(
        STORAGE_PATH, experiment_name, groups_updatable
    )

    print("Define response matrix Y and observations and observation error covariance")
    Y, observations, C_D = define_response_and_observations(
        ensemble, observations_and_responses
    )
    print(f"Y.shape:  {Y.shape}")
    print(f"observations.shape:  {observations.shape}")
    print(f"C_D.shape  {C_D.shape}")

    print("Define observation position and localization influence per observation")
    # x_pos, y_pos, x_range, y_range, rotation = \
    # get_localization_params_per_obs(obs_list)

    [X_prior_dict, X_posterior_dict_esmda, param_type, nx, ny, nz] = update_with_esmda(
        storage,
        STORAGE_PATH,
        experiment_name,
        ensemble_name,
        observations,
        C_D,
        Y,
        ensemble_size,
        n_param_per_group,
        groups_with_3d_fields,
        groups_with_2d_fields,
        groups_with_scalars,
        seed=SEED,
        alpha=ALPHA,
        write_stats_params=WRITE_STATS_PARAMS,
    )

    [X_posterior_dict, param_type, nx, ny, nz] = update_with_distance_esmda(
        storage,
        STORAGE_PATH,
        experiment_name,
        ensemble_name,
        observations,
        C_D,
        Y,
        n_param_per_group,
        groups_with_3d_fields,
        groups_with_2d_fields,
        groups_with_scalars,
        seed=SEED,
        alpha=ALPHA,
        nlayer_per_batch=NLAYER_PER_BATCH,
        write_stats_params=WRITE_STATS_PARAMS,
        use_localization=USE_LOCALIZATION,
    )


# --- main ---
if __name__ == "__main__":
    update_with_esmda = monitor_performance(update_with_esmda)
    update_with_distance_esmda = monitor_performance(update_with_distance_esmda)
    main()
