#!/usr/bin/env python
# coding: utf-8

# # Test Distance Based Localization on real cases


import time

import numpy as np
import polars as pl
import xtgeo
import sys
from ert.storage import open_storage

from iterative_ensemble_smoother.esmda import ESMDA
from iterative_ensemble_smoother.experimental import DistanceESMDA

"""
This script will read info to test distance-based localisation from various sources:
1. Prediction of response parameters are fetched from ERT storage
2. Observations are fetched from both storage and also read from file where also
   (x,y) position of well with production data or (x,y) position of
   4D seismic observation point is saved. The two input csv formatted files
   with production data are generated by running a script in 
   RMS workflow where it is possible to get the well positions or average well path
   position (per zone). Well position is taken from RMS well paths while the well production
   observations are currently taken from ERT input observation file for SUMMARY data from
   flow simulator. Seismic observations are read from the FMU project where tables
   of seismic observations with position is available.
   Both observations of production data (corresponding to SUMMARY vectors from flow simulator)
   and seismic observations can be associated with geological zones. If not, the observations
   are assumed to be relevant to update parameters for all geological zones.
   NOTE: Need to create observation input files for RFT and PLT and TRACER data. All these
   data types can be associated with a well position (RFT, PLT) or a set of well positions (TRACER).
3. Ensemble of realizations of all parameters (both scalar and field parameters)
   is fetched from ERT storage.
4. The definition of ERTBOX for each field parameter should be possible to get from storage
   This information is currently defined by a hard-coded dict in this script.

Use of observations:
1. First a dict with all observations are built based on combining the information about
   observations from both storage and external files read. This must be created such that
   it is easy to identify which observations belongs to which zones. Default will be that
   observations belongs to all zones.
2. Secondly, for all observations that cannot be associated with a single position,
   the position data is marked as None existing, but still they must be used.
3. Check if there are zone dependent observations (not available in all zones)
   and define groups of observations per zone.

Responses and observations:
1. For each zone, calculate Y matrix using responses, observation vector and covariance diagonal matrix C_D for observation error.
   If multiple zone use the same set of observations, we can re-use Y, observation vector and C_D instead of re-calculating it. Some data
   structure to handle this should be on the implementation plan. This step will be the first step before running update calculation
   of batches of layers of field parameter values from a field parameter group. But if re-use of Y, observation vector and C_D is possible
   without reaching memory limit, some time will be saved. 

Update steps:
1. Preparation step: Group observations per zone
2. For each geological zone:
    - Get the observation group for the zone.
    - If not yet calculated and available, calculate Y, observation vector, C_D
    - If not yet calculated and available, calculate rho for one layer of the 3D grid.
        The calculation of rho for one layer depends on the observation positions
        and the position of the center point of each grid cell in the ERTBOX laterally (i,j)
        It also depends on parameters for localization ellipse
        (the ellipse principal axes corresponds to main range and perpendicular ranges
        and the ellipse is rotated) for each observation. The influence range parameters
        can be individual per observation. 
        
        For irregularly distributed observation points like observations coming from
        production data from wells, the calculation of rho for one grid layer of the parameters
        is done by using numpy mesh in distance calculations.
        For regularly spaced observations (typically seismic observation points), it is
        more efficient to only calculate rho for pairs of field parameter values and
        seismic observation points by calculating ranges of indices in the ertbox grid and
        the seismic grid (if the seismic grid which is usually a 2D grid) is aligned with 
        the ERTBOX (same rectangular area as a layer of ERTBOX as seen in map view (xy- cross section)).
        The resolution (the spacing) between seismic observation points in local x and y direction
        within the ERTBOX can be different from the ERTBOX. Utilize the regular grid structure
        of seismic data (assuming it is aligned with ERTBOX) reduce the need for calculating
        distance between all pairs of grid cell center points of ERTBOX, which is the position of
        the field parameter values, and each individual observation point of the seismic observation.

        Note: For observation with None as position (for instance region observations
        like fluid contacts, production observation for regions or the whole reservoir)
        rho for these type of observation is 1 for all field parameter values in
        a group or even for all parameter groups depending on whether the observation
        is limited to specified zone(s). If the user want to limit the non-local observations
        influence radius around some user specified position, it should be possible for the
        user to specify this, but default should be that region related observations are non-local
        and will have influence on all parameters.(Corresponds to infinite localization ranges)
    - Initialize smoother object
    - Calculate all steps that only depends on Y and observations and C_D as a preparation step
    - Loop over parameters and for 3D field parameters:
        - Loop over batches of layers of field parameter values from a field parameter group
        - Within the loop, copy rho for one layer into all layers in the batch of layers to get
          the rho for the update
        - Run assimilate to calculate the update for this batch
        - Repeat for all batches of layers of field parameters

The optimization of the algorithm is here related to:
1. Calculate rho for one layer for a 3D field parameter and copy it into the other layers
   since distance is only calculated laterally (z coordinate is not used), but still observations
   can be limited to update a subset of all geological zones, so in that sense it may be depth dependent,
   but only on a coarse scale (zone scale). To take care of this we have the loop over zones.

   The calculation of rho for one layer can be optimized if observations (like seismic observation points)
   and the field parameter is aligned within ERTBOX. This means that both field parameter and seismic obs
   are regularly spaced and can be calculated in the same local coordinate system defined by ERTBOX.
   A local coordinate system is defined by the ERTBOX. The ERTBOX coordinate system is defined by
   a corner point (lower left) (xorigo, yorigo) in global coordinates (e.g. UTM coordinates). A rotation
   of the ERTBOX define the rotation of the local coordinate system relative to the global coordinate system.
   Note that in general ERTBOX coordinate system may vary from field parameter to field parameter, but
   usually the ERTBOX coordinate system is the same for all zones while the grid resolution of the ERTBOX grid
   may vary from zone to zone, in particular the number of layers, nz. Some calculations can be saved by knowing if
   all field parameters share the same definition of the ERTBOX coordinate system or not, which means that
   (xorigo, yorigo, rotation) is the same and that the grid resolution laterally (xinc, yinc, nx, ny ) is the same.
   A position of a field parameter witin ERTBOX coordinate is 
     xpos =  (i+0.5) * xinc
     ypos =  (j+0.5) * yinc
   where local origo is (0,0) and is the same position as the rotation point (xorigo, yorigo)
   for ERTBOX relative to the global coordinate system.

   Observation position is translated and rotated to get the coordinates in ERTBOX coordinate system.
     a. Translate observation position to lower left corner point of ERTBOX (if ERTBOX is not rotated)
     b. Rotate to the local coordinate axes of the ERTBOX
   
   After position of observations are transformed into ERTBOX coordinates, it is possible to calculate
   distances between observations and field parameter grid cells in ERTBOX.
   If seismic data is aligned with the ERTBOX and the rows and columns of
   regularly spaced observation points are oriented in same way as the cell center points in the ERTBOX grid,
   it is relatively easy to calculate intervals of cell indices in i and j direction for the field parameter 
   grid cells within range of a seismic observation. This can speed up the calculation a bit instead of having
   to calculate the distance between each individual seismic point and each individual field parameter position.

   Note: There are currently no information telling ERT which zone a field parameter belongs to.
   Field parameters generated by the APS facies method follow a naming standard where zone name
   is part of the field parameter name. Example: aps_<zone_name>_<gaussian_field_name> like
   aps_Valysar_GRF1. For field parameters related to petrophysical properties (permeability, porosity)
   which is updated simultaneously with gaussian fields used by the APS facies model to create facies,
   a proposal for a naming convention is to use
   <zone_name>_<facies_name>_<petrophysical_name> for field parameters for petrophysical fields
   related to one particular zone and facies.
   For cases where petrophysical properties is used as (transformed) gaussian fields
   and not dependent on facies, the naming convention could be <zone_name>_<petrophysical_name>.
   If we use a naming convention like this, ERT can without any additional information identify
   which 3D field parameters belongs to which geological zone. If no naming standard is required
   it is need for an additional information where zone name is specified per FIELD keyword in ERT config file.
   In the current script, which zone a field parameter group belongs to is hard-coded in a dict.

   NOTE: In the update algorithm it is required (for efficiency) and for calculation of rho that we know
   which type of parameter a parameter group is. This information is also lacking in the storage?
   But maybe it is possible to infer it from the data types used? In the current script, the info about
   which type of parameter each group belongs to is hard-coded in a dict. The parameter types are either
   specified by keyword FIELD (3D), SURFACE (2D) or GEN_KW (scalar parameters). Depending on the type,
   different calculations of rho and of batching is applied.
   Scalar parameters are not updated by distance-based smoother algorithm,
   but can be updated by Adaptive smoother algorithm.

2. Calculation of Y, C_D and many steps in the distance-based update algorithm within DistanceESMDA
   can be done once for each field parameter group and not necessary to re-calculate for each batch
   of field parameters belonging to the same field parameter group. If multiple field parameters
   are influenced by the same set of observations, they can use the same Y, C_D and observation vector
   and thereby save run time.

3. Define batches of field parameters to be update simultaneously. Default can be to update all parameters in a
   parameter group together, but if the 3D fields are large, it may be necessary to split the field parameters into
   a set of layers of parameters. The calculation of batch size should then not only depend on current 
   max available memory but rounded down to define a batch of complete set of layers of parameters and avoid including
   e.g 10 complete layers and a fraction of layer number 11. Then choose the batch size to be 10 layers instead.
   It will then be easier to copy rho for one complete layer into the 10 complete layers of parameters for the batch.

4. Optimalization of multiplication of kalmain gain matrix K with innovation.
   a. Since K with localization will contain a lot of 0 values due to the Schur product between rho and K before
      rho is multiplied, time for computation can be saved by avoiding multiplications and additions with 0. Particluarly
      for cases with seismic 4D observations with many observations and short localization range around seismic points,
      rho will contain ver large portion of elements with 0 as value.

   b. For all field parameter values (and other parameters) having 0 in  DeltaM = M - mean(M) due to 0 prior uncertainty
      it is also nt necessary to do the calculations. These two potential optimizations should be taken care of in implementation
      since the last two steps in the assimilation algorithm take most time due to large matrix multiplication when using seismic
      observations.

   c. The last optimalization potential is for cases where there are large portions of inactive field parameters within ERTBOX.
      Today, we have to calculate an update for all field parameters in ERTBOX regardless of whether they are active or not
      since which cells have active field parameter value vary from realization to realization in general case.
      If we modify the calculation of DeltaM = M - mean(M) and only use active values in mean(M), it will be possible to
      update the field parameters only for the active field parameter values within each realization.
      This will also reduce number of multiplications and additions. On the other hand, the filtering operation to select
      which field parameter to update also require some CPU time, so a test for various cases should be done. This optimalization
      is most relevant for geological zones modelled as top or base conform where number of active parameters
      in the geological zone vary from realization to realization due to structural model uncertainty.
      For zones with proportional gridding, also the number of active parameters may vary due to structural model uncertainty
      that varies from realization to realization, but in this case it is typically along staircase faults
      the number of active parameters may vary from realization to realization. 

Drogon case:
1. Assume all observations except RFT and PLT data can update parameters for all zones.
   The lateral influence of an observation will limit how far laterally an observation
   will have effect on field parameters, but vertically 
   the field parameters with (x,y) distance within the localization range is updated.
   For zone dependent data like RFT and PLT, they are only included in observation vector
   for the relevant zones. It is possible to experiment with zone dependence such that
   some observations are only able to update field parameters in one zone and not all 3 zones.
2. The ERTBOX coordinate system is the same for all zones (same lateral definition of ERTBOX). This means
   that coordinate transformation of position of observations is only necessary to be calculated once and
   calculation of rho for one layer can be done once as long as all zones use the same observations.
3. The size of the field parameters (nx * ny * nz_zone_dependent) is small enough that one usually don't have
   to split the update of a parameter group into smaller batches in this case.
4. The naming convention used by APS allow us to identify the zone name for each field parameter group
   but this is in general not the case and therefore a hard-coded dict in this script define the zone per field
   enven though this is not necessary when only using field parameters coming from APS where zone name
   is part of the field parameter name in ERT.
5. Number of active parameters vary from realization to realization in Therys, but not in the other two zones.
   There are no large staircase faults that creates active/inactive field parameters from realization to realization.

What Drogon case cannot test:
1. A more efficient specification of seismic 4D data defined by a regular 2D grid aligned with the ERTBOX
2. No observation related to regions or the reservoir as a whole.
3. No observation of fluid contacts (they are used as parameters with a prior distribution)
4. Drogon size of the field parameters are not very large compared with real reservoir cases.
5. Drogon does not limit updates of 2D SURFACE parameters to observations directly related to volume, but
   is updated by using all observations.
6. Cannot test the effect of having active/inactive values varying from realization to realization along staircase faults.
"""

STORAGE_PATH = (
    "/project/fmu/users/olia/drogon_20250623_11-50/"
    "resmod/ff/25.0.0/ert/output/drogon_ahm/storage"
)

SEED = 42
ALPHA = 1
NLAYER_PER_BATCH = (
    40  # 66 layers in ERTBOX for Drogon which is split into 2 batches here
)
# Turn on/off calculation of rho based on localization or only use rho = 1
USE_LOCALIZATION = False

# Turn on/off export of field parameters into 3D parameter files in ROFF format to be read by RMS.
WRITE_STATS_PARAMS = True

# Common definition of ERTBOX for all zones in Drogon
XORIGO = 456063.69091796875
YORIGO = 5935990.898925781
XINC = 75.17192661654963
YINC = 74.79699019286826
ROTATION = 29.88159640627248
NX = 92
NY = 146
NZ = 66

# Need to distinguish between observation groups.
# NOTE: This should be available from ERT, but is not yet?
# WellObs - Observations from wells with position (prod data etc)"
# GenObs  - Any observation having a location like seismic obs points,
#           gravimetry obs points
# RegionObs - Any observation without any specific coordinate for
#             its location (e.g. region or field prod data,
#             data for average over regions, FWL, GOC which are
#             defined per region)
OBS_TYPES_WITH_LOCATION = ["WellObs", "GenObs"]
OBS_TYPES_WITHOUT_LOCATION = ["RegionObs"]

# Get observations with position and localization ranges from external files
# created by running a script in RMS
OBS_FILE_PATH = (
    "/project/fmu/users/olia/drogon_20250623_11-50/resmod/ff/25.0.0/rms/model/"
)
OBS_FILE = "summary_obs_with_localization_attributes.csv"
OBS_SUMMARY_WITH_LOCAL_ATTRIBUTES_FILE = OBS_FILE_PATH + OBS_FILE

# Hard-coded a classification of parameter groups into scalars, 2D or 3D field parameters
# NOTE: This should be available from ERT storage (ERT knows about the source the keyword FIELD, SURFACE GEN_KW)
#       and could have an attribute in storage for the type of the parameter group.
GROUP_WITH_3D_FIELDS = [
        "aps_Valysar_GRF1",
        "aps_Valysar_GRF2",
        "aps_Valysar_GRF3",
        "aps_Therys_GRF1",
        "aps_Therys_GRF2",
        "aps_Therys_GRF3",
        "aps_Volon_GRF1",
        "aps_Volon_GRF2",
        "aps_Volon_GRF3",
    ]
GROUP_WITH_2D_FIELDS = [
        "TOP_VOLANTIS",
        "TOP_THERYS",
        "TOP_VOLON",
        "BASE_VOLANTIS",
    ]
GROUP_WIHT_SCALARS = [
        "GLOBVAR",
        "MULTREGT",
        "RATE",
    ]

# If we could have naming convention we could get zone name from parameter name.
# We have that for APS parameters:  aps_<zone_name>_<grf_name>),
# In general we don't. A proposal for naming convention for petrophysical field parameters
# (e.g for permeabilit or porosity) could be <zone_name>_<facies>_<petro_name>
# for petrophysical fields to be updated simultaneously with facies update from APS.
# For reservoir zones without facies modelling, the convention could be  <zone_name>_<petro_name>
# NOTE: An additional parameter in FIELD keyword with zone name can solve the problem if naming convention
#       of 3D field parameters is not required. Storage should have zone name as an attribute to each field parameter
ZONE_PER_3D_FIELD_PARAM_GROUP ={
    "aps_Valysar_GRF1": "Valysar",
    "aps_Valysar_GRF2": "Valysar",
    "aps_Valysar_GRF3": "Valysar",
    "aps_Therys_GRF1":  "Therys",
    "aps_Therys_GRF2":  "Therys",
    "aps_Therys_GRF3":  "Therys",
    "aps_Volon_GRF1":   "Volon",
    "aps_Volon_GRF2":   "Volon",
    "aps_Volon_GRF3":   "Volon",
}
# NOTE: ERTBOX should be fetched from the storage, but currently I have specified
# this explicitly here.
#
# Usually ERTBOX definition is the same for all zones (even for NZ), but with the new
# possibility to have individual ERTBOX per geological zone, NZ will usually vary from
# 3D field parameter to 3D field parameter. In more rare cases also
# other ERTBOX definition parameters may vary.
#
# The 3D field parameters belonging to the same zone will also belong to the same ERTBOX.
# Depending on observation and their dependency on geological zones, we can simplify
# the calculation of rho:
# 1. If no observations (from well production or seismic) depends on zone, a common version
#    of Y matrix can be used for all 
#    it means that localization which only here care about lateral distance (x,y)
#    but not depth will need a calculation of rho for only one grid layer of ERTBOX
#    and this can then be copied to all other layers for the rho for the
#    3D field parameters for the zone.
# 2. If some observations are not defined for all zones, it can be both for
#    seismic 4D and well production observation, then a new version of Y
#    is necessary for each zone.

# For some of the field parameters, the ERTBOX will be the same
# for all ERTBOX parameters. This is the case for field parameters
# coming from the same zone. By identifying which parameters belongs to the same zone
# we can avoid having to recalculate rho matrix for each of these 3D parameters.
# If we have to use batches of layers per field parameter, all the batches for all
# field parameters coming from the same zone can fill rho matrix from the same rho calculated
# for one layer of field parameter values. If all observations can update all zones,
# this can be done even more efficient since all 3D field parameters can use the same
# calculated rho for one single layer.
# 
# When ERTBOX is different from field
# parameter to field parameter it is usually because NZ vary
# since the ERTBOX grids for the various zones represents approximately
# the lateral position of a geological grid zone and usually the different
# zones in the geological grid are represented by a multizone grid
# and multi-zone grids usually have the same lateral number of grid cells (NX, NY)
# in each zone. In the most general case, each geological zone has its own geogrid
# with its own orientation, position and resolution and this is possible to represent
# with individual specification of all the ERTBOX parameters per 3D field parameter.
# In Drogon case (running a version before 3D field parameters can have individual ERTBOX)
# all ERTBOX parameters are equal as in the case below. In the new extended implementation
# with individual ERTBOX per 3D field parameter, I assume each zone of Drogon will have 
# its own value of NZ but the rest is the same.
ERTBOX_PER_3D_FIELD_PARAM_GROUP = {
    "aps_Valysar_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Valysar_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Valysar_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Therys_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Therys_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Therys_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Volon_GRF1": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Volon_GRF2": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
    "aps_Volon_GRF3": {
        "xorigo": XORIGO,
        "yorigo": YORIGO,
        "XINC": XINC,
        "YINC": YINC,
        "ROTATION": ROTATION,
        "NX": NX,
        "NY": NY,
        "NZ": NZ,
    },
}
def define_field_param_grid_dict(
    xorigo: float,
    yorigo: float,
    rotation: float,
    xinc: float,
    yinc: float,
    nx: int,
    ny: int,
    nz: int,
) -> dict:
    return {
        "xorigo": xorigo,
        "yorigo": yorigo,
        "rotation": rotation,
        "xinc": xinc,
        "yinc": yinc,
        "nx": nx,
        "ny": ny,
        "nz": nz,
    }


def read_obs_and_localization_range_files(
    summary_obs_file: str, well_localization_attributes_file: str
) -> list[dict]:
    """
    Read info about observations and localization parameters from files generated by
    the script
    """
    print(f"Read file: {summary_obs_file}")
    with open(summary_obs_file, "r") as file:
        line_list = file.readlines()
    obs_list = []
    read_headings = False
    for line in line_list:
        if len(line) == 0:
            continue
        # Assume first non-empty line in the file contains the headings
        if not read_headings:
            read_headings = True
            headings = line.split()
            headings = [heading.strip().lower() for heading in headings]
            continue
        words = line.split()
        record = {}
        for index, heading in enumerate(headings):
            if heading in ["summary_key", "date", "zone"]:
                value = str(words[index].strip())
            else:
                value = float(words[index].strip())
            record[heading] = value
        obs_list.append(record)

    print(f"Read file: {well_localization_attributes_file}")
    with open(well_localization_attributes_file, "r") as file:
        line_list = file.readlines()
    read_headings = False
    obs_localization_attribute_list = []
    for line in line_list:
        if len(line) == 0:
            continue
        # Assume first non-empty line in the file contains the headings
        if not read_headings:
            read_headings = True
            headings = line.split()
            headings = [heading.strip().lower() for heading in headings]
            continue
        words = line.split()
        record = {}
        for index, heading in enumerate(headings):
            if heading in ["summary_key", "zone"]:
                value = str(words[index].strip())
            else:
                value = float(words[index].strip())
            record[heading] = value
        obs_localization_attribute_list.append(record)

    # Merge together attributes with observations
    for obs_dict in obs_list:
        for obs_attribute_dict in obs_localization_attribute_list:
            if (
                obs_dict["summary_key"] == obs_attribute_dict["summary_key"]
                and obs_dict["zone"] == obs_attribute_dict["zone"]
            ):
                obs_dict["xpos"] = obs_attribute_dict["xpos"]
                obs_dict["ypos"] = obs_attribute_dict["ypos"]
                obs_dict["main_range"] = obs_attribute_dict["main_range"]
                obs_dict["perp_range"] = obs_attribute_dict["perp_range"]
                obs_dict["azimuth"] = obs_attribute_dict["azimuth"]
                obs_dict["zone"] = obs_attribute_dict["zone"]
                break
#        print(f"Obs dict after updated with localization data: {obs_dict=}")
    return obs_list

def read_observations_with_localization_attributes(
    filename: str,
):
    """
    Read a csv file with space as separator and generated by RMS containing all
    observations of type SUMMARY with (x,y) position in global (UTM) coordinates
    and localization ranges.
    Return a dataframe.
    """
    df_obs_local_attributes = pl.read_csv(filename, separator=' ')
    return df_obs_local_attributes



def monitor_performance(func):
    """Decorator to monitor time only"""

    def wrapper(*args, **kwargs):
        start_time = time.perf_counter()

        result = func(*args, **kwargs)

        end_time = time.perf_counter()

        print(f"Function {func.__name__}:")
        print(f"  Total time: {end_time - start_time:.2f}s")

        return result

    return wrapper


def update_with_esmda(
    storage,
    storage_path: str,
    experiment_name: str,
    ensemble_name: str,
    observations: np.ndarray,
    C_D: np.ndarray,
    Y: np.ndarray,
    ensemble_size: int,
    n_param_per_group: np.ndarray,
    groups_with_3d_fields: list[str],
    groups_with_2d_fields: list[str],
    groups_with_scalars: list[str],
    seed: int = 42,
    alpha: int = 1,
    write_stats_params: bool = True,
) -> list[dict[str, np.ndarray], dict[str, np.ndarray], int, int, int]:
    # Initialize ESMDA
    print(f"Initialize ESMDA for alpha = {alpha}")
    # Workaround to ensure ESMDA don't fail when repeating call on assimilate
    alpha_workaround = np.zeros((1000), dtype=np.float32)
    alpha_workaround[:] = 1.0
    smoother_ESMDA = ESMDA(
        covariance=C_D, observations=observations, alpha=alpha_workaround, seed=seed
    )
    #    print(f"{observations=}")
    # print(f"Perturb observations for ESMDA")
    # D = smoother_ESMDA.perturb_observations(
    #    ensemble_size=ensemble_size, alpha=alpha
    # )

    print("Loop over all parameter groups and update with ESMDA")
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    X_prior_dict = {}
    X_posterior_dict = {}
    print(f"{n_param_per_group=}")
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name(ensemble_name)
        # ensemble = experiment.get_ensemble_by_name("ensemble")
        # groups = list(experiment.parameter_configuration.keys())
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())

        realizations = ensemble.get_realization_list_with_responses()
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f" Skip group {group_name} which cannot be updated")
                continue

            print(
                f"Process parameter group: {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            if group_name in groups_with_3d_fields:
                print(f" Parameter group {group_name} is a 3D field")
                param_type = "3D"
                nx = param_config_all[group_name].nx
                ny = param_config_all[group_name].ny
                nz = param_config_all[group_name].nz
            elif group_name in groups_with_2d_fields:
                print(f" Parameter group {group_name} is a 2D field")
                param_type = "2D"
                nx, ny, nz = 0, 0, 0
                nx = param_config_all[group_name].ncol
                ny = param_config_all[group_name].nrow
                nz = 1
            elif group_name in groups_with_scalars:
                param_type = "Scalar"
                nx, ny, nz = 0, 0, 0
            else:
                print(
                    f" Warning: {group_name} is of unknown type. Will not be updated."
                )
                continue

            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            print(f"X_group.shape = {X_group.shape}")
            print(f"Y.shape = {Y.shape}")
            assert Y.shape[1] == X_group.shape[1]

            print(" Assimilate")
            X_post_group = smoother_ESMDA.assimilate(X=X_group, Y=Y)
            X_posterior_dict[group_name] = X_post_group
            X_prior_dict[group_name] = X_group

            print(
                f"Complete ESMDA for parameter group {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            print("")
            group_number += 1

            if write_stats_params and param_type == "3D":
                # Optionally, calculate mean stdev and write to file
                mean_prior_param = np.mean(X_group, axis=1)
                stdev_prior_param = np.std(X_group, axis=1)

                mean_post_param = np.mean(X_post_group, axis=1)
                stdev_post_param = np.std(X_post_group, axis=1)
                param_dict = {}
                key = "global_mean_prior_" + group_name
                param_dict[key] = mean_prior_param

                key = "global_std_prior_" + group_name
                param_dict[key] = stdev_prior_param

                key = "global_mean_post_" + group_name
                param_dict[key] = mean_post_param

                key = "global_std_post_" + group_name
                param_dict[key] = stdev_post_param

                write_3d_field_param_to_file(param_dict, nx, ny, nz)
                print("")
    return [X_prior_dict, X_posterior_dict, param_type, nx, ny, nz]


def update_with_distance_esmda(
    storage,
    storage_path: str,
    experiment_name: str,
    ensemble_name: str,
    observations: np.ndarray,
    C_D: np.ndarray,
    Y: np.ndarray,
    n_param_per_group: np.ndarray,
    groups_with_3d_fields: list[str],
    groups_with_2d_fields: list[str],
    groups_with_scalars: list[str],
    seed: int = 42,
    alpha: int = 1,
    nlayer_per_batch: int = 22,
    write_stats_params: bool = True,
    use_localization: bool = False,
) -> list[dict[str, np.ndarray], int, int, int]:
    # ## Ensemble Smoother with Distance Based Localization

    print("")
    print("Start initialize DistanceESMDA")
    if use_localization:
        print(" Use localization")
    else:
        print(
            " Don't use localization but run algorithm for distance-based "
            "localization with RHO = 1"
        )
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    smoother = DistanceESMDA(
        covariance=C_D, observations=observations, alpha=alpha, seed=seed
    )
    smoother.prepare_assimilation(Y, truncation=0.99)

    print("Loop over all parameter groups and update with DistanceESMDA")
    X_posterior_dict = {}
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name(ensemble_name)
        param_config_all = experiment.parameter_configuration
        groups = list(param_config_all.keys())
        realizations = ensemble.get_realization_list_with_responses()
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f" Skip group {group_name} which cannot be updated")
                continue
            print(
                f"Process parameter group: {group_name} with "
                f"{n_param_per_group[group_number]} parameters"
            )
            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            nparam, nreal = X_group.shape
            X_post_group = np.zeros((nparam, nreal), dtype=np.float32)
            if group_name in groups_with_3d_fields:
                print(f" Parameter group {group_name} is a 3D field")
                param_type = "3D"
                nx = param_config_all[group_name].nx
                ny = param_config_all[group_name].ny
                nz = param_config_all[group_name].nz

                print(f" Dimension of 3D parameter: ({nx},{ny},{nz})")

                nbatch = int(nz / nlayer_per_batch)
                nlayer_last_batch = nz - nbatch * nlayer_per_batch
                for batch_number in range(nbatch):
                    start_layer_number = batch_number * nlayer_per_batch
                    end_layer_number = start_layer_number + nlayer_per_batch
                    start = start_layer_number * nx * ny
                    end = end_layer_number * nx * ny
                    X_batch = X_group[start:end, :]

                    print(f" Define rho for 3D field {group_name}")
                    nparam_in_batch = nx * ny * nlayer_per_batch

                    if not use_localization:
                        # rho = 1 without localization
                        rho = np.ones(shape=(nparam_in_batch, Y.shape[0]))  # temporary
                    print(f" rho.shape:  {rho.shape}")
                    assert Y.shape[1] == X_batch.shape[1]

                    print(f" Assimilate batch number {batch_number}")
                    X_post_batch = smoother.assimilate_batch(
                        X_batch=X_batch, Y=Y, rho_batch=rho
                    )
                    X_post_group[start:end, :] = X_post_batch[:]

                if nlayer_last_batch > 0:
                    batch_number = nbatch
                    start_layer_number = batch_number * nlayer_per_batch
                    end_layer_number = start_layer_number + nlayer_last_batch
                    start = start_layer_number * nx * ny
                    end = end_layer_number * nx * ny
                    X_batch = X_group[start:end, :]

                    print(f" Define rho for 3D field {group_name}")
                    nparam_in_batch = nx * ny * nlayer_last_batch
                    rho = np.ones(shape=(nparam_in_batch, Y.shape[0]))  # temporary
                    print(f" rho.shape:  {rho.shape}")
                    assert Y.shape[1] == X_batch.shape[1]

                    print(f" Assimilate batch number {batch_number}")
                    X_post_batch = smoother.assimilate_batch(
                        X_batch=X_batch, Y=Y, rho_batch=rho
                    )
                    X_post_group[start:end, :] = X_post_batch[:]

            elif group_name in groups_with_2d_fields:
                print(f" Parameter group {group_name} is a 2D field")
                param_type = "2D"
                nx = param_config_all[group_name].ncol
                ny = param_config_all[group_name].nrow
                nz = 1
                print(f" Define rho for 2D field {group_name}")
                rho = np.ones(shape=(X_group.shape[0], Y.shape[0]))  # temporary
                print(f" rho.shape:  {rho.shape}")

                X_group = ensemble.load_parameters_numpy(group_name, realizations)
                assert Y.shape[1] == X_group.shape[1]
                print(" Assimilate")
                X_post_group = smoother.assimilate_batch(
                    X_batch=X_group, Y=Y, rho_batch=rho
                )

            elif group_name in groups_with_scalars:
                param_type = "Scalar"
                nx, ny, nz = 0, 0, 0
                X_post_group = None
                print(
                    f" Skip scalar parameter group {group_name} "
                    "in distance-based localization"
                )
            else:
                print(
                    f" Warning: {group_name} is of unknown type. Will not be updated."
                )
                continue

            X_posterior_dict[group_name] = [X_post_group, param_type, nx, ny, nz]

            print(
                f"Complete DistanceESMDA for parameter group {group_name} "
                f"with {n_param_per_group[group_number]} parameters"
            )
            print("")
            group_number += 1

            if write_stats_params and param_type == "3D":
                # Optionally, calculate mean stdev and write to file
                mean_post_param = np.mean(X_post_group, axis=1)
                stdev_post_param = np.std(X_post_group, axis=1)
                param_dict = {}

                key = "local_mean_post_" + group_name
                param_dict[key] = mean_post_param

                key = "local_std_post_" + group_name
                param_dict[key] = stdev_post_param

                write_3d_field_param_to_file(param_dict, nx, ny, nz)
                print("")
    return [X_posterior_dict, param_type, nx, ny, nz]


def define_response_and_observations(
    ensemble,
    observations_and_responses,
    df_obs_with_localization_attributes,
):
    """
    Calculate Y matrix, C_D matrix and observation vector
    """
    print(f"Columns in observations_and_responses: {observations_and_responses.columns}")
    print(f"Columns in df_obs: {df_obs_with_localization_attributes.columns}")
    print(f"Column from observations_and_response: {observations_and_responses.get_column('observation_key')}")
    print(f"Column from df_obs: {df_obs_with_localization_attributes.get_column('ert_id')}")
    # For alle ert_id (som heter observation_key) finn samme ert_id i den dataframe fra fil
    # og legg til lokaliseringsattributtene til observations_and_responses.
    # Deretter ta ut xpos, ypos, main_range, perp_range og azimuth
    # i egne numpy arrays akkurat som values som ender opp i observations numpy vektoren.
    sys.exit(0)

    response_cols = [
        str(i) for i in range(1, ensemble.ensemble_size)
    ]  # Why from 1 and not 0?
    # response_cols = [str(i) for i in range(0, ensemble.ensemble_size)]

    # Here responses with 0 std is not included?
    df_filtered = observations_and_responses.filter(
        pl.concat_list([pl.col(col) for col in response_cols])
        .list.eval(pl.element().std())
        .list.first()
        > 0
    )
    print(df_filtered)
    
    Y = df_filtered.select(
        pl.all().exclude(
            ["response_key", "index", "observation_key", "observations", "std"]
        )
    ).to_numpy()


    observations = df_filtered["observations"].to_numpy()
    std = df_filtered["std"].to_numpy()
    C_D = std**2

    # Returner også xpos, ypos, main_range, perp_range, azimuth.
    # For observasjoner som ikke har definert disse, sett udefinert.
    # Hvis udefinert er funnet for lokaliseringsattributtene til en obs,
    #men observasjonen er definert, så må det bety at denne observasjonen ikke er lokalisert
    # og dermed skal rho være lik 1 for alle par av denne observasjonen og feltparametrene
    #
    return Y, observations, C_D


def write_3d_field_param_to_file(
    param_dict: dict[str, np.ndarray],
    nx: int,
    ny: int,
    nz: int,
    output_path: str = "TMP",
) -> None:
    """
    Write 3D parameter to ROFF format file to be readable by RMS
    """
    for param_name, values in param_dict.items():
        xtgeo_param = xtgeo.GridProperty(
            ncol=nx, nrow=ny, nlay=nz, name=param_name, values=values
        )
        file_name = output_path + "/" + param_name + ".roff"
        print(f"Write file: {file_name}")
        xtgeo_param.to_file(file_name, fformat="roff")


def calculate_rho_for_one_layer_of_3d_field(
    ertbox_dict: dict,
    obs_list: list,
):
    """
    Input:
    Specification of ERTBOX for the field
    (xorigo, yorigo,rotation,xinc,yinc,nx,ny,nz)
    For each observation, position, localization range
    (rotated to the local coordinate system defined by ERTBOX)
    type of observation (well observation, seismic observation,
    other observation types without position) scaling function (tapering function)
    for each observation for current field parameters

    Output: rho for one layer with nx * ny field parameter values for all observations
    having position.
    """
    # Center points of each grid cell in field parameter grid
    # in local coordinate system (ertbox grid)
    x_local = np.arange(ertbox_dict.nx)
    x_local = (x_local + 0.5) * ertbox_dict.xinc
    y_local = np.arange(ertbox_dict.ny)
    y_local = (y_local + 0.5) * ertbox_dict.yinc
    mesh_y_local, mesh_x_coord = np.meshgrid(y_local, x_local, indexing="ij")
    # for obs_nr, obs
    # #for obs_nr, obs_pos
    # #for obs_pos in observation_positions:
    # dX = grid_x_coord - obs_xpos
    # dY = grid_y_coord - obs_ypos
    # rotation = ellipse_rotation * np.pi / 180.0
    # cosangle = math.cos(rotation)
    # sinangle = math.sin(rotation)
    # #    print(f"shape of dX: {dX.shape} ")
    # #    print(f"shape of dY: {dY.shape} ")
    # dX_ellipse = (dX * cosangle + dY * sinangle) / main_range
    # dY_ellipse = (-dX * sinangle + dY * cosangle) / perp_range
    # distances_2d = np.sqrt(dX_ellipse * dX_ellipse + dY_ellipse * dY_ellipse)
    # distances = distances_2d.flatten()
    # scaling_factors = scaling_function(distances)


def get_number_of_groups_and_parameters(
    storage_path: str, experiment_name: str, groups_updatable: list[str]
) -> list[int, list[int]]:
    n_param_total = 0
    n_param_per_group = []
    with open_storage(storage_path, "r") as storage:
        experiment = storage.get_experiment_by_name(experiment_name)
        ensemble = experiment.get_ensemble_by_name("ensemble")
        groups = list(experiment.parameter_configuration.keys())
        realizations = ensemble.get_realization_list_with_responses()
        assert ensemble.ensemble_size == len(realizations)
        group_number = 0
        for group_name in groups:
            if group_name not in groups_updatable:
                print(f"Skip group {group_name} which cannot be updated")
                continue

            X_group = ensemble.load_parameters_numpy(group_name, realizations)
            nparam = X_group.shape[0]
            n_param_total += nparam
            n_param_per_group.append(nparam)
            print(
                f" Number of param in group {group_number}"
                f" with name {group_name} is {nparam}"
            )
            group_number += 1
    return n_param_total, n_param_per_group


def main():

    with open_storage(STORAGE_PATH) as storage:
        [print(f"Available experiment names: {x.name}") for x in storage.experiments]

    # ## Pick which experiment to analyse
    experiment_name = "ensemble_experiment"
    ensemble_name = "ensemble"

    # Load observations and responses from storage.
    # Remove responses with zero standard deviation
    print("Get observations and responses")
    with open_storage(STORAGE_PATH, "r") as storage:
        ensemble = storage.get_experiment_by_name(experiment_name).get_ensemble_by_name(
            "ensemble"
        )
        ensemble_size = ensemble.ensemble_size
        selected_obs = ensemble.experiment.observation_keys
        iens_active_index = np.array(ensemble.get_realization_list_with_responses())
        observations_and_responses = ensemble.get_observations_and_responses(
            selected_obs, iens_active_index
        )
        #print(observations_and_responses.glimpse(return_as_string=True))
        #for i, response in enumerate(observations_and_responses["response_key"]):
        #
        #     print(f"response: {response} observation_key: {observation_key}")
        #print(f"selected_obs: {selected_obs}")
        #print(f"observations_and_responses:  {observations_and_responses}")
        #    sys.exit(0)
    #obs_list = read_obs_and_localization_range_files(
    #    OBS_SUMMARY_FILE, OBS_LOCAL_ATTRIBUTE_FILE
    #)
    df_obs_with_local = read_observations_with_localization_attributes(OBS_SUMMARY_WITH_LOCAL_ATTRIBUTES_FILE)
    #print(df_obs_with_local)
    
    # Define type of parameter (scalars, 2D, 3D parameter)
    # skip_groups = ["SWITCHES", "DESIGN_MATRIX"]
    groups_with_3d_fields = [
        "aps_Valysar_GRF1",
        "aps_Valysar_GRF2",
        "aps_Valysar_GRF3",
        "aps_Therys_GRF1",
        "aps_Therys_GRF2",
        "aps_Therys_GRF3",
        "aps_Volon_GRF1",
        "aps_Volon_GRF2",
        "aps_Volon_GRF3",
    ]
    groups_with_2d_fields = [
        "TOP_VOLANTIS",
        "TOP_THERYS",
        "TOP_VOLON",
        "BASE_VOLANTIS",
    ]
    groups_with_scalars = [
        "GLOBVAR",
        "MULTREGT",
        "RATE",
    ]
    groups_updatable = (
        groups_with_3d_fields + groups_with_2d_fields + groups_with_scalars
    )
    # print(f"{groups_updatable=}")
    print(
        "Get number of updatable parameter groups "
        "and number of parameters per updatable group"
    )
    n_param_total, n_param_per_group = get_number_of_groups_and_parameters(
        STORAGE_PATH, experiment_name, groups_updatable
    )

    print("Define response matrix Y and observations and observation error covariance")
    Y, observations, C_D = define_response_and_observations(
        ensemble, observations_and_responses, df_obs_with_local,
    )
    print(f"Y.shape:  {Y.shape}")
    print(f"observations.shape:  {observations.shape}")
    print(f"C_D.shape  {C_D.shape}")

    print("Define observation position and localization influence per observation")


    [X_prior_dict, X_posterior_dict_esmda, param_type, nx, ny, nz] = update_with_esmda(
        storage,
        STORAGE_PATH,
        experiment_name,
        ensemble_name,
        observations,
        C_D,
        Y,
        ensemble_size,
        n_param_per_group,
        groups_with_3d_fields,
        groups_with_2d_fields,
        groups_with_scalars,
        seed=SEED,
        alpha=ALPHA,
        write_stats_params=WRITE_STATS_PARAMS,
    )

    [X_posterior_dict, param_type, nx, ny, nz] = update_with_distance_esmda(
        storage,
        STORAGE_PATH,
        experiment_name,
        ensemble_name,
        observations,
        C_D,
        Y,
        n_param_per_group,
        groups_with_3d_fields,
        groups_with_2d_fields,
        groups_with_scalars,
        seed=SEED,
        alpha=ALPHA,
        nlayer_per_batch=NLAYER_PER_BATCH,
        write_stats_params=WRITE_STATS_PARAMS,
        use_localization=USE_LOCALIZATION,
    )


# --- main ---
if __name__ == "__main__":
    update_with_esmda = monitor_performance(update_with_esmda)
    update_with_distance_esmda = monitor_performance(update_with_distance_esmda)
    main()
