name: Build docs
permissions:
  contents: read

on: [pull_request]

env:
  UV_FROZEN: true # https://docs.astral.sh/uv/configuration/environment/#uv_frozen

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.14' ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          prune-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Install SuiteSparse
        run: sudo apt-get install -y libsuitesparse-dev

      - name: Build docs
        run: |
          uv sync --extra doc
          uv run python -m ipykernel install --user
          uv run sphinx-build -c docs/source/ -b html docs/source/ docs/build/html -W
