name: Build docs

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install tox
        run: pip install tox

      - name: Build docs
        run: tox -e docs
