name: Pre-commit tests
permissions:
  contents: read

on: [push, pull_request]

env:
  UV_FROZEN: true # https://docs.astral.sh/uv/configuration/environment/#uv_frozen

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.14' ]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          enable-cache: true
          prune-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Install SuiteSparse
        run: sudo apt-get install -y libsuitesparse-dev

      - run: uv sync --extra dev --extra sparse

      - name: Check precommit
        run: uv run pre-commit run --all-files --show-diff-on-failure
