name: Pre-commit tests
permissions:
  contents: read

on: [push, pull_request]

env:
  UV_FROZEN: true # https://docs.astral.sh/uv/configuration/environment/#uv_frozen

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.14' ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          prune-cache: false
          python-version: ${{ matrix.python-version }}

      - run: uv sync --extra dev

      - name: Check precommit
        run: uv run pre-commit run --all-files --show-diff-on-failure
